import type { SubjectId, TeachingMode } from "./prompts";

export type CourseSource = {
  id: string;
  title: string;
  titleEn: string;
  url: string;
  publisher: string;
  access: string;
};

export type CourseModule = {
  id: string;
  subject: SubjectId;
  level: "L1" | "L2" | "L3" | "L4" | "L5" | "L6";
  title: string;
  titleEn: string;
  overview: string;
  overviewEn: string;
  inquiry: string;
  inquiryEn: string;
  sourceIds: string[];
};

export const COURSE_SOURCES: CourseSource[] = [
  { id: "lit-fiction", title: "《散文小说：叙事符号学导论》", titleEn: "Prose Fiction: An Introduction to the Semiotics of Narrative", url: "https://open.umn.edu/opentextbooks/textbooks/prose-fiction-an-introduction-to-the-semiotics-of-narrative", publisher: "Open Textbook Library", access: "CC BY" },
  { id: "lit-world", title: "《世界文学简明选集》", titleEn: "Compact Anthology of World Literature", url: "https://open.umn.edu/opentextbooks/textbooks/410", publisher: "Open Textbook Library", access: "Open textbook" },
  { id: "lit-gutenberg", title: "古腾堡计划公共领域原典", titleEn: "Project Gutenberg public-domain texts", url: "https://www.gutenberg.org/", publisher: "Project Gutenberg", access: "Public domain / free access" },
  { id: "econ-openstax", title: "《经济学原理 3e》", titleEn: "Principles of Economics 3e", url: "https://openstax.org/details/books/principles-economics-3e", publisher: "OpenStax · Rice University", access: "CC BY-NC-SA 4.0" },
  { id: "econ-core", title: "CORE Econ 开放经济学课程", titleEn: "CORE Econ open courses", url: "https://www.core-econ.org/", publisher: "CORE Econ", access: "Free educational access" },
  { id: "psych-openstax", title: "《心理学 2e》", titleEn: "Psychology 2e", url: "https://openstax.org/details/books/psychology-2e", publisher: "OpenStax · Rice University", access: "CC BY-NC-SA 4.0" },
  { id: "psych-noba", title: "Noba 心理学开放模块", titleEn: "Noba Psychology modules", url: "https://nobaproject.com/modules", publisher: "Noba Project", access: "Free educational access" },
  { id: "business-writing", title: "《成功商务沟通》", titleEn: "Business Communication for Success", url: "https://open.umn.edu/opentextbooks/textbooks/business-communication-for-success", publisher: "Open Textbook Library", access: "CC BY-NC-SA" },
  { id: "business-management", title: "《管理学原理》", titleEn: "Principles of Management", url: "https://open.umn.edu/opentextbooks/textbooks/principles-of-management", publisher: "Open Textbook Library", access: "CC BY-NC-SA" },
  { id: "business-org", title: "《组织行为学》", titleEn: "Organizational Behavior", url: "https://openstax.org/details/books/organizational-behavior", publisher: "OpenStax · Rice University", access: "Free open textbook" },
  { id: "daily-cefr", title: "欧洲语言共同参考框架能力描述", titleEn: "CEFR descriptors", url: "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors", publisher: "Council of Europe", access: "Free official reference" },
  { id: "daily-wikivoyage", title: "维基导游旅行会话资源", titleEn: "Wikivoyage travel phrase resources", url: "https://en.wikivoyage.org/wiki/Phrasebooks", publisher: "Wikivoyage", access: "CC BY-SA" },
  { id: "daily-eu", title: "欧盟 Your Europe 公共服务指南", titleEn: "Your Europe public-service guides", url: "https://europa.eu/youreurope/citizens/index_en.htm", publisher: "European Union", access: "Free official reference" },
  { id: "art-met", title: "海尔布伦艺术史时间线", titleEn: "Heilbrunn Timeline of Art History", url: "https://www.metmuseum.org/essays/timeline-of-art-history", publisher: "The Metropolitan Museum of Art", access: "Free scholarly reference" },
  { id: "art-smarthistory", title: "Smarthistory 全球艺术史", titleEn: "Smarthistory global art history", url: "https://smarthistory.org/", publisher: "Smarthistory", access: "CC BY-NC-SA" },
  { id: "phil-sep", title: "斯坦福哲学百科全书", titleEn: "Stanford Encyclopedia of Philosophy", url: "https://plato.stanford.edu/", publisher: "Stanford University", access: "Free scholarly reference" },
  { id: "phil-iep", title: "互联网哲学百科全书", titleEn: "Internet Encyclopedia of Philosophy", url: "https://iep.utm.edu/", publisher: "University of Tennessee at Martin", access: "Free scholarly reference" },
  { id: "science-algorithms", title: "MIT 6.006 算法导论", titleEn: "MIT 6.006 Introduction to Algorithms", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/", publisher: "MIT OpenCourseWare", access: "CC BY-NC-SA" },
  { id: "science-distributed", title: "MIT 6.824 分布式系统", titleEn: "MIT 6.824 Distributed Systems", url: "https://ocw.mit.edu/courses/6-824-distributed-computer-systems-engineering-spring-2006/", publisher: "MIT OpenCourseWare", access: "CC BY-NC-SA" },
  { id: "science-dl", title: "MIT 深度学习导论", titleEn: "MIT Introduction to Deep Learning", url: "https://ocw.mit.edu/courses/6-s191-introduction-to-deep-learning-january-iap-2020/", publisher: "MIT OpenCourseWare", access: "CC BY-NC-SA" },
  { id: "science-quantum", title: "MIT 8.04 量子物理 I", titleEn: "MIT 8.04 Quantum Physics I", url: "https://ocw.mit.edu/courses/8-04-quantum-physics-i-spring-2016/", publisher: "MIT OpenCourseWare", access: "CC BY-NC-SA" },
  { id: "science-physics", title: "《大学物理》", titleEn: "University Physics", url: "https://openstax.org/details/books/university-physics-volume-1", publisher: "OpenStax · Rice University", access: "CC BY-NC-SA 4.0" },
];

const m = (
  id: string,
  subject: SubjectId,
  level: CourseModule["level"],
  title: string,
  titleEn: string,
  overview: string,
  overviewEn: string,
  inquiry: string,
  inquiryEn: string,
  sourceIds: string[],
): CourseModule => ({ id, subject, level, title, titleEn, overview, overviewEn, inquiry, inquiryEn, sourceIds });

export const COURSE_MODULES: CourseModule[] = [
  m("lit-l1-1", "literature", "L1", "短篇小说：叙述者、视角与可靠性", "Short fiction: narrator, focalization and reliability", "先把作者、叙述者与人物分开，再观察信息由谁看见、何时透露。第一人称并不天然可靠，第三人称也不等于全知；视角是作品分配知识与同情的技术。", "Separate author, narrator and character, then track who perceives each event and when information is released. First person is not automatically reliable, and third person is not automatically omniscient; perspective distributes knowledge and sympathy.", "把同一事件分别写成当事人、旁观者与后来调查者的三段叙述，哪些事实发生了变化？", "Retell one event as a participant, a witness and a later investigator. Which facts appear to change?", ["lit-fiction", "lit-world"]),
  m("lit-l1-2", "literature", "L1", "诗歌入门：节奏、声音与意象", "Poetry basics: rhythm, sound and image", "诗歌不是把散文切成短行。行分割、重音、重复、押韵与停顿共同制造期待；意象则把抽象判断转化为可感知的关系。阅读时应先听结构，再解释象征。", "Poetry is not prose broken into short lines. Lineation, stress, repetition, rhyme and pause create expectation, while imagery turns abstractions into perceptible relations. Hear the structure before assigning symbols.", "删掉一首短诗中的换行后，意义、速度和强调发生了什么变化？", "Remove the line breaks from a short poem. What changes in meaning, pace and emphasis?", ["lit-world", "lit-gutenberg"]),
  m("lit-l1-3", "literature", "L1", "戏剧与悲剧：行动、冲突与净化", "Drama and tragedy: action, conflict and catharsis", "从亚里士多德开始，悲剧研究关注的不是坏事堆积，而是行动如何因选择、知识限制与逆转形成整体。净化并非简单的情绪发泄，而是关于观众如何重组恐惧与怜悯的争论。", "Since Aristotle, tragedy has concerned the organization of action through choice, limited knowledge and reversal rather than a pile-up of misfortunes. Catharsis is debated as a reorganization of fear and pity, not mere emotional discharge.", "如果结局相同，角色是否知情会怎样改变悲剧效果？", "If the ending is unchanged, how does the character's knowledge alter the tragic effect?", ["lit-world", "lit-gutenberg"]),
  m("lit-l2-1", "literature", "L2", "《浮士德》：求索、契约与现代主体", "Faust: striving, contract and the modern subject", "把 Faust 的求索理解为现代性的矛盾：知识与行动不断扩张，却无法保证判断更成熟。契约既是情节装置，也是欲望把未来抵押给即时可能性的形式。", "Read Faustian striving as a contradiction of modernity: knowledge and action expand without guaranteeing wiser judgment. The contract is both plot device and a form in which desire mortgages the future to immediate possibility.", "求知欲在什么条件下从德性转化为逃避责任？", "Under what conditions does the desire to know turn from a virtue into an evasion of responsibility?", ["lit-gutenberg", "lit-world"]),
  m("lit-l2-2", "literature", "L2", "象征、隐喻与多义性", "Symbol, metaphor and polysemy", "隐喻建立跨域关系，象征则依靠作品和文化中的反复出现累积意义。高质量解释不能把意象翻译成唯一答案，而要说明哪些文本证据支持哪些解释、哪些解释彼此竞争。", "Metaphor maps relations across domains; symbols accumulate meaning through recurrence within a work and culture. Strong interpretation does not translate an image into one answer but shows which evidence supports competing readings.", "怎样区分有证据的多义解释与不受约束的联想？", "How can evidence-based plurality be distinguished from unconstrained association?", ["lit-fiction", "lit-world"]),
  m("lit-l2-3", "literature", "L2", "世界文学：流通、翻译与不对称", "World literature: circulation, translation and asymmetry", "世界文学不是经典书单，而是作品跨越语言、市场与教育制度时发生的再编码。需要同时研究译者选择、出版网络、中心—边缘关系，以及某些文本为何比另一些更容易被翻译。", "World literature is not a canon list but the recoding that occurs as works cross languages, markets and educational institutions. Study translators' choices, publishing networks, center–periphery relations and unequal translatability.", "一本书在全球流通，是因为它普遍，还是因为制度把它塑造成了‘普遍’？", "Does a book circulate globally because it is universal, or because institutions make it appear universal?", ["lit-world", "lit-fiction"]),
  m("lit-l3-1", "literature", "L3", "形式主义：陌生化与文学性", "Formalism: defamiliarization and literariness", "形式主义把注意力从作者意图转向文本如何运作。陌生化不是把事物写得古怪，而是延长感知、暴露习惯化语言；专家阅读还要追问形式分析忽略了哪些历史与权力条件。", "Formalism shifts attention from authorial intention to textual operation. Defamiliarization is not mere oddity but a prolonging of perception that exposes habitual language; advanced reading also asks what history and power formal analysis leaves out.", "同一种修辞技术在广告与诗歌中使用时，‘文学性’还成立吗？", "When the same device appears in advertising and poetry, does literariness still hold?", ["lit-fiction", "lit-world"]),
  m("lit-l3-2", "literature", "L3", "结构主义与符号学：差异如何生成意义", "Structuralism and semiotics: meaning through difference", "符号的意义来自系统中的差异关系，而非词与物的天然粘合。分析要区分能指、所指、代码与语境，并检验二元结构何时有解释力、何时会抹平历史变化。", "A sign gains meaning through differential relations within a system, not a natural bond between word and thing. Distinguish signifier, signified, code and context, then test when binary structures explain and when they flatten history.", "一个符号能否在没有共享代码的情况下被理解？", "Can a sign be understood without a shared code?", ["lit-fiction", "phil-sep"]),
  m("lit-l3-3", "literature", "L3", "后殖民阅读：声音、翻译与知识权力", "Postcolonial reading: voice, translation and epistemic power", "后殖民批评研究谁被允许代表谁、帝国分类如何进入叙事、翻译怎样制造可读性。成熟分析既不能把文本还原为政治口号，也不能把审美形式与殖民历史分开。", "Postcolonial criticism asks who may represent whom, how imperial classifications enter narrative and how translation manufactures legibility. Mature analysis reduces neither text to slogan nor form to something separable from colonial history.", "当被压迫者必须使用统治者的语言发言时，表达获得了什么，又失去了什么？", "When the oppressed must speak in the ruler's language, what is gained and what is lost?", ["lit-world", "lit-fiction"]),

  m("econ-l1-1", "economics", "L1", "稀缺、选择与机会成本", "Scarcity, choice and opportunity cost", "经济学从约束下的选择开始。机会成本不是支付的金额，而是所放弃的最佳替代方案；沉没成本则不应影响边际决策。先明确决策者、可选项和时间范围。", "Economics begins with choice under constraint. Opportunity cost is not the money paid but the best forgone alternative; sunk costs should not govern marginal decisions. Identify decision-maker, alternatives and time horizon first.", "一个‘免费’在线课程的机会成本可能是什么？", "What might be the opportunity cost of a free online course?", ["econ-openstax", "econ-core"]),
  m("econ-l1-2", "economics", "L1", "供给、需求与市场均衡", "Supply, demand and market equilibrium", "供需模型解释的是在其他条件不变时，价格与数量如何协调。必须区分曲线上的移动与整条曲线移动，并把均衡理解为相容状态，而不是公平或理想状态。", "The supply–demand model explains coordination of price and quantity under ceteris paribus. Distinguish movement along a curve from a shift of the curve, and treat equilibrium as mutual compatibility, not fairness or optimality.", "租金上限改变的是市场均衡、住房质量，还是两者？如何判断？", "Does rent control change market equilibrium, housing quality or both, and how would you tell?", ["econ-openstax", "econ-core"]),
  m("econ-l1-3", "economics", "L1", "比较优势、专业化与贸易", "Comparative advantage, specialization and trade", "比较优势比较的是机会成本而非绝对生产率。互利贸易可以与分配冲突同时存在；模型说明总收益的可能性，却不保证损失者自动得到补偿。", "Comparative advantage compares opportunity costs, not absolute productivity. Gains from trade can coexist with distributional conflict; the model establishes possible aggregate gains but does not compensate losers automatically.", "如果贸易提高总产出却让某一地区长期衰退，‘互利’应如何重新表述？", "If trade raises total output while one region declines for decades, how should mutual benefit be reformulated?", ["econ-openstax", "econ-core"]),
  m("econ-l2-1", "economics", "L2", "通货膨胀、指数与货币政策", "Inflation, indices and monetary policy", "通胀是总体价格水平持续上升，不等于某一种商品涨价。理解 CPI 要检查消费篮子、权重和基期；分析政策则要区分需求、供给冲击、预期与传导时滞。", "Inflation is a sustained rise in the general price level, not one expensive item. To interpret CPI inspect basket, weights and base year; to assess policy distinguish demand, supply shocks, expectations and transmission lags.", "同样的 CPI 通胀率为什么会让不同家庭感受完全不同？", "Why can the same CPI inflation rate feel radically different across households?", ["econ-openstax", "econ-core"]),
  m("econ-l2-2", "economics", "L2", "失业、产出与经济周期", "Unemployment, output and business cycles", "失业率依赖劳动力人口定义，下降既可能来自就业增长，也可能来自退出劳动力市场。周期分析要结合参与率、工时、实际产出与部门差异，不能靠单一指标判断。", "The unemployment rate depends on the labor-force definition; it can fall through job growth or labor-force exit. Cycle analysis should combine participation, hours, real output and sectoral differences rather than one indicator.", "怎样设计一个不会被单一统计口径误导的就业仪表盘？", "How would you design an employment dashboard that cannot be misled by one statistic?", ["econ-openstax", "econ-core"]),
  m("econ-l2-3", "economics", "L2", "财政政策、赤字与公共债务", "Fiscal policy, deficits and public debt", "赤字是流量，债务是存量；公共债务也不能直接类比家庭借款。评价可持续性要看币种、利率、期限、增长、税基与支出用途，同时说明代际与分配影响。", "A deficit is a flow and debt a stock; sovereign debt is not simply household borrowing. Sustainability depends on currency, rates, maturity, growth, tax base and use of funds, together with distributional and intergenerational effects.", "用于基础设施与用于填补低效支出的同额债务，经济意义是否相同？", "Does equal debt used for infrastructure and inefficient current spending have the same economic meaning?", ["econ-openstax", "econ-core"]),
  m("econ-l3-1", "economics", "L3", "博弈论：策略、承诺与纳什均衡", "Game theory: strategy, commitment and Nash equilibrium", "纳什均衡是任何参与者单独改变策略都无法获益的策略组合，不保证合作、效率或道德可取。建模必须写清参与者、信息、行动顺序、收益与可信承诺。", "A Nash equilibrium is a strategy profile in which no player benefits from unilateral deviation; it need not be cooperative, efficient or desirable. Specify players, information, timing, payoffs and credible commitments.", "怎样改变规则而不是劝说参与者，才能让囚徒困境产生更好结果？", "How can changing rules rather than exhorting players improve a prisoner's dilemma?", ["econ-core", "econ-openstax"]),
  m("econ-l3-2", "economics", "L3", "行为经济学：偏差、助推与证据", "Behavioral economics: bias, nudges and evidence", "行为经济学研究系统性偏离标准模型的选择模式。不能把每次非理性都命名为偏差；需要可重复证据、明确基准，并评估助推的透明度、分配后果与操纵风险。", "Behavioral economics studies systematic departures from benchmark models. Not every mistake is a bias: claims require replicable evidence and a clear benchmark, while nudges require scrutiny of transparency, distribution and manipulation.", "默认选项什么时候是帮助，什么时候是不正当操纵？", "When is a default helpful, and when is it illegitimate manipulation?", ["econ-core", "psych-openstax"]),
  m("econ-l3-3", "economics", "L3", "制度、债务语言与全球治理", "Institutions, debt language and global governance", "债务同时是合同、资产负债表关系和道德叙事。跨语比较 debt、dette、Schuld 与 debito 可以暴露政策修辞，但词源不能代替制度分析；最终仍要看债权、货币与谈判权力。", "Debt is simultaneously contract, balance-sheet relation and moral narrative. Comparing debt, dette, Schuld and debito reveals policy rhetoric, but etymology cannot replace institutional analysis of claims, currency and bargaining power.", "债务危机被描述为‘过错’而非‘风险分配失败’时，谁会获益？", "Who benefits when a debt crisis is framed as fault rather than failed risk allocation?", ["econ-core", "econ-openstax"]),

  m("psych-l1-1", "psychology", "L1", "心理学方法：测量、相关与因果", "Psychological methods: measurement, correlation and causation", "心理学结论依赖操作化：抽象构念如何变成可观察指标。相关不推出因果，实验也要检查随机分配、样本代表性、效应大小、可重复性与伦理限制。", "Psychological conclusions depend on operationalization—how constructs become observable measures. Correlation is not causation, and experiments still require scrutiny of randomization, representativeness, effect size, replication and ethics.", "把‘幸福’变成研究变量时，你会测量什么，又会漏掉什么？", "If happiness becomes a research variable, what would you measure and what would be lost?", ["psych-openstax", "psych-noba"]),
  m("psych-l1-2", "psychology", "L1", "学习：经典条件反射与操作性条件作用", "Learning: classical and operant conditioning", "经典条件反射学习刺激之间的关系，操作性条件作用学习行为与后果之间的关系。强化增加行为，惩罚减少行为；正负表示加入或移除，不表示好坏。", "Classical conditioning learns relations among stimuli; operant conditioning learns relations between behavior and consequences. Reinforcement increases behavior and punishment decreases it; positive and negative mean adding and removing, not good and bad.", "为什么暂时压制行为不等于真正改变了学习机制？", "Why does temporary suppression of behavior not prove that learning has changed?", ["psych-openstax", "psych-noba"]),
  m("psych-l1-3", "psychology", "L1", "注意、工作记忆与长期记忆", "Attention, working memory and long-term memory", "注意是有限选择机制，工作记忆负责短时保持与操作，长期记忆涉及编码、巩固与提取。遗忘常是提取失败或线索改变，并非信息被简单擦除。", "Attention is limited selection; working memory temporarily maintains and manipulates information; long-term memory involves encoding, consolidation and retrieval. Forgetting often reflects retrieval failure or changed cues, not simple erasure.", "反复阅读为什么常让人产生‘我已经掌握’的错觉？", "Why does repeated reading often create an illusion of mastery?", ["psych-openstax", "psych-noba"]),
  m("psych-l2-1", "psychology", "L2", "发展、依恋与环境", "Development, attachment and environment", "发展是生物成熟、关系与文化环境持续互动的过程。依恋类型是研究模型而非终身标签；个体路径具有可塑性，研究结论也不能脱离照料制度与社会条件。", "Development is an interaction among maturation, relationships and cultural environments. Attachment classifications are research models, not lifelong labels; trajectories remain plastic and findings depend on care systems and social conditions.", "什么时候‘早期经历很重要’会被误读为‘早期经历决定一切’？", "When does early experience matters get misread as early experience determines everything?", ["psych-openstax", "psych-noba"]),
  m("psych-l2-2", "psychology", "L2", "人格：特质、情境与预测", "Personality: traits, situations and prediction", "特质模型描述相对稳定的差异，却不能解释全部行为。预测需要同时考虑人格、情境强度、测量误差和时间尺度，避免把量表分数当作人的本质。", "Trait models describe relatively stable differences but do not explain all behavior. Prediction combines person, situational strength, measurement error and timescale; a scale score is not a person's essence.", "招聘中使用人格测验，需要哪些效度、公平与隐私证据？", "What validity, fairness and privacy evidence is needed before using personality tests in hiring?", ["psych-openstax", "business-org"]),
  m("psych-l2-3", "psychology", "L2", "心理治疗：认知行为模型与疗效证据", "Psychotherapy: cognitive-behavioral models and evidence", "认知行为治疗把思想、情绪、行为与环境视为可相互影响的系统。理解疗效要看适应证、对照组、治疗联盟、复发与不良反应；课程内容不能替代专业诊断或治疗。", "Cognitive-behavioral therapy treats thoughts, emotions, behavior and environment as interacting systems. Evidence requires indications, controls, therapeutic alliance, relapse and adverse effects; educational content never replaces professional diagnosis or care.", "‘改变想法’为什么不是要求痛苦者进行积极思考？", "Why is changing thoughts not the same as demanding positive thinking from someone in distress?", ["psych-openstax", "psych-noba"]),
  m("psych-l3-1", "psychology", "L3", "弗洛伊德：Es、Ich 与 Über-Ich", "Freud: Es, Ich and Über-Ich", "弗洛伊德的德语是日常代词：它、我、超我。拉丁化译名让理论更专业，也遮蔽了原文的亲近感；应把这一结构当作历史理论模型，而不是可直接测量的脑区。", "Freud's German uses ordinary pronouns: it, I and over-I. Latinized translations professionalize the theory but obscure its intimacy; treat the structure as a historical theoretical model, not measurable brain regions.", "术语翻译变得更专业时，理论获得了什么权威，又失去了什么经验质感？", "When translation sounds more technical, what authority is gained and what experiential texture is lost?", ["psych-openstax", "phil-sep"]),
  m("psych-l3-2", "psychology", "L3", "社会心理学：从众、服从与情境", "Social psychology: conformity, obedience and situation", "经典实验说明情境压力可以强烈影响行为，但复现实验、文化差异与研究伦理会改变解释边界。不能用‘人性如此’替代对权威结构、规范与责任分散的分析。", "Classic studies show strong situational influence, but replication, culture and research ethics constrain interpretation. Human nature is not a substitute for analyzing authority structures, norms and diffusion of responsibility.", "解释伤害行为时，强调情境会不会削弱个人责任？", "Does emphasizing situation weaken personal responsibility when explaining harm?", ["psych-openstax", "psych-noba"]),
  m("psych-l3-3", "psychology", "L3", "身份、自我叙事与文化", "Identity, self-narrative and culture", "自我并非单一故事，也不是任意虚构。记忆、社会角色、身体经验与文化叙事共同限制可讲述的身份；研究需要区分个人意义、群体分类与制度赋予的身份。", "The self is neither one story nor arbitrary fiction. Memory, social roles, embodiment and cultural narratives constrain narratable identity; analysis distinguishes personal meaning, group categories and institutionally assigned identity.", "当一个人的自我故事与社会分类冲突时，谁有解释权？", "Who has interpretive authority when a person's self-story conflicts with social classification?", ["psych-noba", "psych-openstax"]),

  m("biz-l1-1", "business", "L1", "商务写作：目的、受众与行动", "Business writing: purpose, audience and action", "商务文本先解决行动问题：读者是谁、需要做什么、何时完成、凭什么判断。主题行、首段和结尾应形成同一行动链；礼貌不能以模糊责任为代价。", "Business writing begins with action: who must do what, by when and according to what criterion. Subject line, opening and close should form one action chain; courtesy must not blur responsibility.", "把一封冗长邮件压缩到读者能在十秒内识别行动要求。你删掉了什么？", "Compress a long email so the action is visible in ten seconds. What did you remove?", ["business-writing"]),
  m("biz-l1-2", "business", "L1", "会议：议程、决策与纪要", "Meetings: agenda, decisions and minutes", "会议不是同步汇报的默认容器。议程应说明决策点、输入材料和负责人；纪要要区分讨论、决定、行动项与未解决风险，并记录截止时间。", "A meeting is not the default container for status updates. Agendas specify decision points, inputs and owners; minutes distinguish discussion, decisions, actions and unresolved risks with deadlines.", "什么信息应该异步共享，什么问题值得占用所有人的同步时间？", "What belongs in asynchronous updates, and what deserves everyone's synchronous time?", ["business-writing", "business-management"]),
  m("biz-l1-3", "business", "L1", "反馈、冲突与困难对话", "Feedback, conflict and difficult conversations", "有效反馈描述可观察行为、影响与下一步，而不是给人格贴标签。困难对话要同时维护事实准确、关系尊重和行动边界，并允许对方补充信息。", "Effective feedback describes observable behavior, impact and next steps rather than labeling personality. Difficult conversations maintain factual accuracy, respect and boundaries while allowing new information.", "怎样表达‘这个结果不合格’，又不把判断偷换成‘你不行’？", "How can you say this result is inadequate without turning it into you are inadequate?", ["business-writing", "business-org"]),
  m("biz-l2-1", "business", "L2", "谈判：立场、利益与备选方案", "Negotiation: positions, interests and alternatives", "立场是说出口的要求，利益是背后的需要，BATNA 是谈不成时的最佳替代。分析锚定与让步时，还要检查信息不对称、权力与长期关系。", "Positions are stated demands, interests are underlying needs, and BATNA is the best alternative to agreement. Anchors and concessions must be analyzed with information asymmetry, power and long-term relationships.", "如果对方的 BATNA 很弱，利用它与维持长期合作之间如何权衡？", "If the other side has a weak BATNA, how should leverage be balanced against long-term cooperation?", ["business-management", "business-org"]),
  m("biz-l2-2", "business", "L2", "敏捷工作：迭代、反馈与复盘", "Agile work: iteration, feedback and retrospectives", "敏捷不是更快开会，而是缩短假设到证据的循环。迭代要有可验证增量、明确完成标准和真实用户反馈；复盘讨论系统条件而非寻找替罪者。", "Agile is not faster meetings but a shorter loop from assumption to evidence. Iterations require testable increments, a definition of done and real user feedback; retrospectives examine systems rather than scapegoats.", "团队每两周交付很多内容，却从未验证用户价值，这算敏捷吗？", "A team ships a great deal every two weeks but never tests user value. Is it agile?", ["business-management", "business-org"]),
  m("biz-l2-3", "business", "L2", "战略：价值主张、取舍与定位", "Strategy: value proposition, trade-offs and positioning", "战略不是愿望清单，而是面对约束做出相互支持的取舍。价值主张必须说明为谁解决什么问题、为何优于替代方案，以及组织选择不做什么。", "Strategy is not a wish list but mutually reinforcing trade-offs under constraint. A value proposition identifies whose problem is solved, why the offer beats alternatives and what the organization chooses not to do.", "如果一个产品声称适合所有人，它实际上放弃了哪些战略判断？", "If a product claims to serve everyone, which strategic judgments has it avoided?", ["business-management", "business-writing"]),
  m("biz-l3-1", "business", "L3", "决策：证据、不确定性与反对意见", "Decision-making: evidence, uncertainty and dissent", "高层决策要分离事实、预测、偏好与不可逆风险。决策备忘录应记录假设、置信度、反方观点、触发复审的信号，以及谁承担结果。", "Executive decisions separate facts, forecasts, preferences and irreversible risks. A decision memo records assumptions, confidence, dissenting views, review triggers and accountability for outcomes.", "怎样设计一个让反对意见真正影响决策、而非只被礼貌记录的流程？", "How can dissent genuinely affect a decision rather than be politely recorded?", ["business-management", "business-org"]),
  m("biz-l3-2", "business", "L3", "危机沟通：速度、准确与信任", "Crisis communication: speed, accuracy and trust", "危机中沉默也会传递信息。首轮沟通应说明已知、未知、正在采取的行动和下一次更新时间；绝不能用确定语气掩盖证据不足。", "Silence communicates during a crisis. The first message should distinguish knowns, unknowns, actions and the next update time; certainty must never be performed when evidence is incomplete.", "‘避免恐慌’什么时候会变成隐瞒关键风险的借口？", "When does preventing panic become an excuse to hide material risk?", ["business-writing", "business-org"]),
  m("biz-l3-3", "business", "L3", "跨文化领导：规范、权力与翻译", "Cross-cultural leadership: norms, power and translation", "文化框架只能生成假设，不能给个人定型。领导者要观察发言顺序、拒绝方式、等级距离与冲突规范，并建立可被纠正的工作协议。", "Cultural frameworks generate hypotheses, not stereotypes about individuals. Leaders observe turn-taking, refusal, hierarchy and conflict norms, then create working agreements that can be corrected.", "团队把沉默理解为同意，但部分成员把沉默当作礼貌，决策程序应如何改变？", "A team reads silence as consent while some members use silence as courtesy. How should decision procedures change?", ["business-org", "business-writing", "daily-cefr"]),

  m("daily-l1-1", "daily", "L1", "抵达与问路：确认而非猜测", "Arrival and directions: confirm, do not guess", "生存沟通的目标不是说得复杂，而是降低误解。先说明目的地，再确认方向、站名、换乘和时间；用复述验证关键数字与地名。", "The goal of survival communication is not complexity but reduced misunderstanding. State the destination, confirm direction, stop, transfer and time, then read back critical numbers and names.", "设计一段即使听漏一个词也能通过复述恢复信息的问路对话。", "Design a directions exchange that can recover from one missed word through read-back.", ["daily-cefr", "daily-wikivoyage"]),
  m("daily-l1-2", "daily", "L1", "餐饮：需求、过敏与确认", "Dining: requests, allergies and confirmation", "偏好与过敏不能混为一谈。说明过敏原、严重程度和交叉接触风险，并要求对方明确确认；礼貌形式要服务于准确，而不是弱化安全信息。", "Preference and allergy must not be conflated. Name the allergen, severity and cross-contact risk, and request explicit confirmation; politeness must support rather than weaken safety.", "怎样用最少的句子区分‘我不喜欢花生’和‘花生会危及生命’？", "How can the fewest sentences distinguish dislike of peanuts from a life-threatening allergy?", ["daily-cefr", "daily-wikivoyage"]),
  m("daily-l1-3", "daily", "L1", "住宿与紧急求助", "Accommodation and emergency help", "求助时先给位置、事件、当前危险和需要的帮助，再补充细节。住宿投诉则要记录房号、问题、发生时间和希望的解决方式，避免只表达不满。", "When seeking help, give location, event, present danger and requested assistance before details. For accommodation complaints record room, problem, timing and desired resolution rather than expressing dissatisfaction alone.", "在压力下，哪些信息必须放在第一句话？", "Under stress, which information must be in the first sentence?", ["daily-cefr", "daily-eu", "daily-wikivoyage"]),
  m("daily-l2-1", "daily", "L2", "租房：合同、押金与书面证据", "Housing: contracts, deposits and written evidence", "租房术语高度依赖司法辖区。语言学习应帮助识别租金、押金、期限、维修、解约与清单，而不能冒充法律意见；重要约定要保留书面记录。", "Housing vocabulary is jurisdiction-specific. Language learning should identify rent, deposit, term, repairs, termination and inventory without pretending to give legal advice; material agreements require written records.", "看房时，哪些口头承诺必须要求写入合同？", "Which verbal promises during a viewing must be written into the contract?", ["daily-cefr", "daily-eu"]),
  m("daily-l2-2", "daily", "L2", "就医：症状、时间线与知情确认", "Healthcare: symptoms, timeline and informed confirmation", "描述症状要包含部位、性质、开始时间、变化、严重度、诱因和相关病史。复述药名、剂量与警示能降低风险；课程不提供诊断。", "A symptom account covers location, quality, onset, change, severity, triggers and relevant history. Reading back medication, dose and warnings reduces risk; the course does not diagnose.", "如何把‘我很不舒服’改造成医生可以据此追问的时间线？", "How can I feel unwell become a timeline a clinician can question productively?", ["daily-cefr", "daily-eu"]),
  m("daily-l2-3", "daily", "L2", "银行、行政与正式请求", "Banking, administration and formal requests", "行政沟通要先识别机构、事项、截止日期、材料和案件编号。正式语言的价值是留下可核查的行动请求，而不是堆砌礼貌套语。", "Administrative communication identifies authority, matter, deadline, documents and case number. Formality creates a verifiable request for action rather than a pile of polite formulas.", "怎样写一封能让陌生办事员迅速判断‘谁、什么事、缺什么、何时前’的邮件？", "How can an email let an unfamiliar official see who, what, what is missing and by when?", ["daily-cefr", "daily-eu"]),
  m("daily-l3-1", "daily", "L3", "语用学：礼貌、拒绝与边界", "Pragmatics: politeness, refusal and boundaries", "同一句语法正确的话可能在权力与关系语境中失礼。高级学习要掌握缓和、间接、明确拒绝与修复误解，并能在安全和边界问题上放弃过度委婉。", "A grammatically correct sentence may be pragmatically rude in context. Advanced learners manage mitigation, indirectness, explicit refusal and repair, while abandoning excess politeness when safety or boundaries require clarity.", "什么时候直接说‘不’比使用委婉语更尊重双方？", "When is a direct no more respectful than a euphemism?", ["daily-cefr"]),
  m("daily-l3-2", "daily", "L3", "跨文化互动：观察、假设与修复", "Intercultural interaction: observe, hypothesize and repair", "文化差异不是国家性格表。更可靠的方法是观察具体互动规范，提出暂定假设，并用澄清句修复误读；个体差异始终优先于文化标签。", "Cultural difference is not a table of national personalities. Observe interactional norms, form provisional hypotheses and repair misunderstanding with clarification; individual evidence outranks labels.", "发现对方的礼貌规则与你不同，怎样询问而不把对方异国化？", "How can you ask about different politeness norms without exoticizing the other person?", ["daily-cefr", "daily-wikivoyage"]),
  m("daily-l3-3", "daily", "L3", "多语调解：解释概念而非逐词翻译", "Plurilingual mediation: explain, do not merely translate", "调解是为不同语言背景的人重组信息、解释隐含前提并确认理解。逐词对应常在医疗、行政和文化概念上失败；高级能力是保留功能与风险。", "Mediation reorganizes information, explains implicit assumptions and checks understanding across languages. Word-for-word matching fails especially in medical, administrative and cultural concepts; advanced competence preserves function and risk.", "一个概念没有直接对应词时，怎样判断解释已经足够而又没有越界？", "When a concept lacks a direct equivalent, how do you know the explanation is sufficient without overreaching?", ["daily-cefr"]),

  m("art-l1-1", "art", "L1", "观看方法：描述、分析与解释", "How to look: description, analysis and interpretation", "先描述可见证据，再分析形式关系，最后提出可被证据支持或反驳的解释。把‘我喜欢’与‘作品如何组织观看’分开，是艺术史入门的关键。", "Describe visible evidence first, analyze formal relations second, and only then propose interpretations open to support or challenge. Separating I like it from how the work organizes looking is foundational.", "对一件作品只写可见事实，不使用任何价值形容词；你遗漏了什么，又避免了什么？", "Describe a work using only visible facts and no value adjectives. What is lost, and what error is avoided?", ["art-met", "art-smarthistory"]),
  m("art-l1-2", "art", "L1", "构图、尺度与视觉重心", "Composition, scale and visual weight", "构图研究元素如何引导视线、建立层级与产生稳定或紧张。视觉重心不等于画面中心；尺度也既是物理大小，也是人物和观众之间的权力关系。", "Composition studies how elements direct attention, establish hierarchy and create stability or tension. Visual weight is not the geometric center, and scale is both physical size and a power relation among figure, object and viewer.", "裁掉画面边缘的一个元素，叙事与重心如何改变？", "Crop one edge element from an image. How do narrative and balance change?", ["art-met", "art-smarthistory"]),
  m("art-l1-3", "art", "L1", "色彩、明度、材料与肌理", "Color, value, material and texture", "色相、明度与饱和度必须分开讨论；材料与制作痕迹也会影响意义。不要把颜色心理学当作普遍字典，应结合照明、颜料、时代与文化语境。", "Hue, value and saturation must be distinguished, while material and traces of making also carry meaning. Color psychology is not a universal dictionary; interpretation depends on light, pigment, period and culture.", "同一种红色在祭祀、广告和警示系统中为何不能共享一个固定含义？", "Why can the same red not keep one fixed meaning across ritual, advertising and warning systems?", ["art-met", "art-smarthistory"]),
  m("art-l2-1", "art", "L2", "文艺复兴：透视、人体与观看秩序", "Renaissance: perspective, body and visual order", "线性透视是一套把画面空间与特定观看点协调起来的技术，不是视觉进步的终点。应同时研究赞助、宗教功能、古典复兴与不同地区的工作坊制度。", "Linear perspective coordinates pictorial space with a particular viewing point; it is not the endpoint of visual progress. Study patronage, religious function, classical revival and regional workshop systems together.", "透视制造的‘自然空间’其实要求观众站在哪里？", "Where must the viewer stand for perspective's natural space to work?", ["art-met", "art-smarthistory"]),
  m("art-l2-2", "art", "L2", "印象派：光、时间与现代生活", "Impressionism: light, time and modern life", "印象派的松动笔触与综合色研究瞬时观看，也与颜料技术、城市改造、展览制度和休闲阶层相连。不能只把它讲成‘画光’。", "Impressionist broken brushwork and optical color investigate transient seeing, while depending on pigment technology, urban redesign, exhibition systems and leisure classes. It is more than painting light.", "一幅看似轻松的城市休闲画面隐藏了哪些劳动与阶级条件？", "What labor and class conditions lie behind an apparently leisurely urban scene?", ["art-met", "art-smarthistory"]),
  m("art-l2-3", "art", "L2", "现代主义：媒介、自律与断裂", "Modernism: medium, autonomy and rupture", "现代主义包含多条相互冲突的路线：形式自律、技术实验、政治先锋与非西方形式的挪用。所谓断裂需要与学院、殖民网络和大众媒介一起分析。", "Modernism contains conflicting projects: formal autonomy, technical experiment, political avant-garde and appropriation of non-Western forms. Rupture must be studied with academies, colonial networks and mass media.", "宣称与传统决裂的作品，仍依赖哪些旧制度才能被看见？", "Which inherited institutions make a work declaring rupture visible at all?", ["art-met", "art-smarthistory"]),
  m("art-l3-1", "art", "L3", "图像学、社会史与视觉文化", "Iconography, social history and visual culture", "图像学识别母题与传统，社会史研究生产与使用条件，视觉文化扩展到广告、摄影与界面。专家分析要让方法互相校正，而不是用单一理论解释一切。", "Iconography identifies motifs and traditions, social history studies production and use, and visual culture expands toward advertising, photography and interfaces. Expert analysis lets methods correct one another rather than using one theory for everything.", "同一图像在博物馆、宗教空间和社交媒体中还是同一件作品吗？", "Is the same image the same work in a museum, sacred space and social feed?", ["art-met", "art-smarthistory"]),
  m("art-l3-2", "art", "L3", "审美判断：康德、趣味与公共性", "Aesthetic judgment: Kant, taste and publicity", "康德的无利害并非没有感受，而是不把对象据为己有的愉悦；趣味判断又提出一种希望他人同意的普遍要求。现代批评还要检查谁拥有形成‘共同趣味’的制度权力。", "Kantian disinterest is not lack of feeling but pleasure without possessing the object; judgments of taste nevertheless solicit universal agreement. Modern criticism asks who has institutional power to define common taste.", "当审美判断声称普遍时，它如何面对阶级、教育与殖民历史？", "How can a claim to universal taste confront class, education and colonial history?", ["phil-sep", "art-met"]),
  m("art-l3-3", "art", "L3", "博物馆、策展与艺术制度", "Museums, curation and art institutions", "收藏、分类、展签与陈列顺序共同生产艺术史。研究博物馆既要看保存与公共教育，也要看掠夺、所有权、缺席与归还争议。", "Collecting, classification, labels and display sequences jointly produce art history. Study museums as preservation and public education, but also through extraction, ownership, absence and restitution.", "一件被归还原属地的文物，其艺术史意义会发生什么变化？", "How does an object's art-historical meaning change after restitution?", ["art-met", "art-smarthistory"]),

  m("phil-l1-1", "philosophy", "L1", "论证入门：前提、结论与反例", "Arguments: premises, conclusions and counterexamples", "哲学论证不是意见的堆积。先把前提与结论写清，再区分有效性与前提真实性；反例只需展示一个结论不随前提必然成立的可能情形。", "A philosophical argument is not a collection of opinions. State premises and conclusion, distinguish validity from truth of premises, and use a counterexample to show a possible case where the conclusion does not follow.", "一个结论正确的论证，为什么仍可能是坏论证？", "Why can an argument with a true conclusion still be bad?", ["phil-iep", "phil-sep"]),
  m("phil-l1-2", "philosophy", "L1", "苏格拉底、柏拉图与哲学生活", "Socrates, Plato and the philosophical life", "苏格拉底式追问检验定义与生活是否一致；柏拉图的对话把论证嵌入人物、场景与失败。学习重点不是背结论，而是追踪问题如何迫使概念修正。", "Socratic questioning tests whether definitions cohere with life; Plato's dialogues embed argument in character, scene and failure. The task is not memorizing conclusions but tracking how questions force conceptual revision.", "承认无知是知识的起点，还是一种修辞优势？", "Is acknowledging ignorance the beginning of knowledge or a rhetorical advantage?", ["phil-sep", "phil-iep"]),
  m("phil-l1-3", "philosophy", "L1", "亚里士多德：解释、四因与德性", "Aristotle: explanation, four causes and virtue", "四因说区分材料、形式、动力与目的等解释维度，不是四种彼此竞争的单一原因。德性伦理则把好生活理解为在实践中形成判断能力。", "The four causes distinguish material, formal, efficient and final dimensions of explanation rather than four rival single causes. Virtue ethics understands a good life through judgment cultivated in practice.", "解释一把椅子和解释一个制度时，四种原因还能同样使用吗？", "Can the four causes explain a chair and an institution in the same way?", ["phil-sep", "phil-iep"]),
  m("phil-l2-1", "philosophy", "L2", "认识论：知识、理由与怀疑", "Epistemology: knowledge, justification and skepticism", "认识论研究知识、证成与理解。‘被证明为真’并不足以穷尽知识，因为偶然的真信念可能缺乏适当联系；怀疑论则检验我们能要求多强的理由。", "Epistemology studies knowledge, justification and understanding. A true belief can still be accidentally true and lack the right connection; skepticism tests how demanding our reasons may be.", "如果一个可靠系统给出结论但你不理解过程，你是否知道答案？", "If a reliable system gives a result whose process you do not understand, do you know the answer?", ["phil-sep", "phil-iep"]),
  m("phil-l2-2", "philosophy", "L2", "伦理学：后果、义务与德性", "Ethics: consequences, duties and virtues", "功利主义、义务论与德性伦理提出不同的评价单位：后果、行动原则与行动者品格。成熟分析应寻找它们冲突的案例、隐藏假设和可修正之处。", "Utilitarian, deontological and virtue approaches evaluate consequences, principles of action and character. Mature analysis identifies conflict cases, hidden assumptions and possible revisions.", "救一个人还是救五个人的思想实验，遗漏了哪些制度与关系事实？", "What institutional and relational facts are omitted by the one-versus-five rescue thought experiment?", ["phil-sep", "phil-iep"]),
  m("phil-l2-3", "philosophy", "L2", "康德：先验条件、现象与物自体", "Kant: transcendental conditions, appearance and thing-in-itself", "先验问题不是超自然问题，而是经验与知识何以可能的条件。现象不是幻觉，物自体也不是躲在物体背后的另一件东西；二者标记认知条件与限度。", "A transcendental question asks not about the supernatural but about conditions that make experience and knowledge possible. Appearances are not illusions, and the thing-in-itself is not another object hiding behind objects; the distinction marks cognitive conditions and limits.", "承认认识受条件限制，会导致相对主义，还是更严格的客观性？", "Does conditioned knowledge lead to relativism or to a stricter account of objectivity?", ["phil-sep", "phil-iep"]),
  m("phil-l3-1", "philosophy", "L3", "黑格尔：否定、承认与 Aufhebung", "Hegel: negation, recognition and Aufhebung", "Aufhebung 同时有取消、保存与提升的语义张力，不能缩成‘正反合’口诀。辩证运动要从概念内部矛盾与承认关系中追踪，而非把任何变化都叫辩证法。", "Aufhebung holds together cancellation, preservation and elevation and cannot be reduced to thesis–antithesis–synthesis. Dialectical movement must be traced through internal contradiction and recognition, not applied to any change.", "一个观点被‘克服’时，哪些内容必须被保存，才不是简单抛弃？", "When a position is overcome, what must be preserved so that it is not merely discarded?", ["phil-sep", "phil-iep"]),
  m("phil-l3-2", "philosophy", "L3", "现象学：意向性、身体与世界", "Phenomenology: intentionality, body and world", "现象学描述经验如何显现，而不是收集主观感受。意向性说明意识总是关于某物；身体不是纯客体，而是我们拥有方向、能力与世界的方式。", "Phenomenology describes how experience appears rather than collecting subjective feelings. Intentionality means consciousness is consciousness of something; the body is not merely an object but our orientation, ability and access to a world.", "把身体只看作可测量物体，会遗漏哪些第一人称结构？", "What first-person structures disappear when the body is treated only as a measurable object?", ["phil-sep", "phil-iep"]),
  m("phil-l3-3", "philosophy", "L3", "存在主义：自由、处境与责任", "Existentialism: freedom, situation and responsibility", "存在主义的自由不是想做什么就做什么，而是在无法选择的处境中仍要回应和承担。萨特、波伏瓦等人的分歧提醒我们，自由必须与身体、他人和压迫结构一起思考。", "Existential freedom is not doing whatever one wants but responding and assuming responsibility within unchosen situations. Differences among Sartre, Beauvoir and others require freedom to be thought with embodiment, others and oppression.", "结构限制越强，谈个人责任越残酷，还是越必要？", "As structural constraint grows, does talk of personal responsibility become crueler or more necessary?", ["phil-sep", "phil-iep"]),

  m("sci-l1-1", "science", "L1", "科学推理：模型、测量与不确定性", "Scientific reasoning: models, measurement and uncertainty", "科学模型是有目的的简化，不是现实的缩小复制。测量必须报告单位、精度、误差来源与适用范围；结果的确定性不能高于数据和模型允许的程度。", "A scientific model is a purposeful simplification, not a miniature copy of reality. Measurement reports units, precision, error sources and scope; conclusions cannot be more certain than data and model permit.", "一个预测很准确的模型，是否因此解释了现象？", "Does accurate prediction mean that a model explains the phenomenon?", ["science-physics", "science-algorithms"]),
  m("sci-l1-2", "science", "L1", "算法、数据结构与复杂度", "Algorithms, data structures and complexity", "算法是解决一类问题的有限、明确步骤；数据结构决定可高效执行的操作。复杂度研究输入规模增长时资源如何增长，不是只测某台电脑跑了几秒。", "An algorithm is a finite, unambiguous procedure for a class of problems; data structures determine efficient operations. Complexity studies resource growth with input size, not seconds on one machine.", "两个程序在小数据上同样快，怎样判断哪一个更可扩展？", "Two programs are equally fast on small data. How do you decide which scales?", ["science-algorithms"]),
  m("sci-l1-3", "science", "L1", "逻辑门、二进制与计算抽象", "Logic gates, binary and computational abstraction", "布尔逻辑把连续物理信号抽象为离散状态，逻辑门组合成算术、存储与控制。抽象隐藏实现细节，但工程师必须知道噪声、时序与能耗何时会重新出现。", "Boolean logic abstracts continuous physical signals into discrete states; gates compose arithmetic, memory and control. Abstraction hides implementation detail, but noise, timing and energy eventually return.", "一个逻辑上正确的电路为什么仍可能在真实硬件中失败？", "Why can a logically correct circuit fail in real hardware?", ["science-algorithms", "science-physics"]),
  m("sci-l2-1", "science", "L2", "经典力学：状态、定律与建模", "Classical mechanics: state, laws and modeling", "牛顿定律在选定参考系和尺度下联系力与运动。解题不是套公式：先定义系统边界、画受力图、选择坐标，再检查量纲、极限与近似。", "Newtonian laws relate force and motion within chosen frames and scales. Problem solving is not formula matching: define system boundaries, draw forces, choose coordinates, then check dimensions, limits and approximations.", "把空气阻力忽略掉是错误，还是有条件的模型选择？", "Is neglecting air resistance an error or a conditional modeling choice?", ["science-physics"]),
  m("sci-l2-2", "science", "L2", "分布式系统：一致性、可用性与故障", "Distributed systems: consistency, availability and failure", "分布式系统没有共同瞬时时钟，消息会延迟、重复或丢失，节点会独立故障。正确性必须说明故障模型、一致性语义与可恢复状态，不能只画云架构图。", "Distributed systems lack a shared instantaneous clock; messages delay, duplicate or disappear, and nodes fail independently. Correctness requires a failure model, consistency semantics and recoverable state—not just a cloud diagram.", "当网络分区发生时，系统应该拒绝服务还是接受可能过期的写入？", "During a network partition, should a system refuse service or accept potentially stale writes?", ["science-distributed"]),
  m("sci-l2-3", "science", "L2", "神经网络：表示、损失与反向传播", "Neural networks: representation, loss and backpropagation", "神经网络通过参数化函数学习表示；损失函数定义训练优化的目标，反向传播高效计算梯度。模型学到的是数据与目标共同塑造的规律，不是自动获得理解。", "Neural networks learn representations through parameterized functions; a loss defines the optimization target and backpropagation computes gradients efficiently. What is learned is shaped by data and objective, not automatic understanding.", "训练误差持续下降而真实表现变差，哪些环节可能出了问题？", "Training error falls while real-world performance worsens. Which parts of the pipeline may be failing?", ["science-dl", "science-algorithms"]),
  m("sci-l3-1", "science", "L3", "量子力学：态、叠加与测量", "Quantum mechanics: states, superposition and measurement", "量子态编码可观测结果的概率结构，叠加是向量空间性质，不等于宏观物体‘同时拥有两个确定状态’。测量问题涉及理论形式、解释与实验可检验性的区分。", "A quantum state encodes the probability structure of observations; superposition is a vector-space property, not a macroscopic object possessing two definite states at once. The measurement problem separates formalism, interpretation and empirical testability.", "两种解释给出相同实验预测时，争论仍然是科学问题吗？", "If two interpretations make identical predictions, is their dispute still scientific?", ["science-quantum", "science-physics"]),
  m("sci-l3-2", "science", "L3", "大模型：规模、能力与评估", "Large models: scale, capability and evaluation", "大模型能力来自架构、数据、目标、规模与后训练的共同作用。‘涌现’可能是真实阈值，也可能是评估尺度造成的视觉效果；结论需要透明基准、消融和误差分析。", "Large-model capability arises jointly from architecture, data, objectives, scale and post-training. Emergence may be a real threshold or an artifact of metric choice; claims require transparent benchmarks, ablations and error analysis.", "模型在基准上得分更高，为什么不等于它在真实任务中更可靠？", "Why does a higher benchmark score not imply greater real-world reliability?", ["science-dl", "science-algorithms"]),
  m("sci-l3-3", "science", "L3", "技术风险：可解释性、安全与治理", "Technology risk: interpretability, safety and governance", "技术风险分析要把危害、暴露、概率、可逆性和责任主体分开。可解释性不是单一功能，可能服务调试、审计、申诉或科学理解；治理措施应与具体风险模型对应。", "Technology-risk analysis separates hazard, exposure, probability, reversibility and accountable actors. Interpretability is not one feature: it may serve debugging, audit, appeal or scientific understanding; governance must match a concrete risk model.", "一个系统无法解释但统计上更准确时，在哪些场景仍不应部署？", "When should a statistically more accurate but opaque system still not be deployed?", ["science-dl", "science-distributed", "phil-sep"]),

  m("lit-l4-1", "literature", "L4", "叙事学方法：时间、频率与话语层级", "Narratological method: time, frequency and levels of discourse", "叙事学把故事发生的顺序与讲述顺序分开，并用时长、频率、嵌套层级分析叙事如何组织经验。方法不是术语清单：每个判断都要落到具体句法、场景转换与信息分配。", "Narratology separates story order from discourse order and studies duration, frequency and embedded levels. The method is not a glossary: every claim must be tied to syntax, scene transition and information distribution.", "同一事件只发生一次却被讲述三次时，重复改变的是事实还是解释权？", "When one event occurs once but is narrated three times, does repetition change fact or interpretive authority?", ["lit-fiction", "lit-world"]),
  m("lit-l4-2", "literature", "L4", "比较诗学：格律、声音与不可译性", "Comparative poetics: meter, sound and untranslatability", "比较诗学不把不同传统强行塞进同一格律表，而是比较重音、音节、声调、押韵和书写系统如何制造形式期待。翻译分析要说明保留了什么、牺牲了什么，以及替代形式的理由。", "Comparative poetics does not force traditions into one metrical grid; it compares how stress, syllable, tone, rhyme and script create formal expectation. Translation analysis states what is preserved, sacrificed and formally substituted.", "译诗保留意义却失去节奏，还是同一首诗吗？", "Is a translation that preserves meaning but loses rhythm still the same poem?", ["lit-world", "lit-gutenberg"]),
  m("lit-l4-3", "literature", "L4", "档案与版本：手稿、校勘和生成批评", "Archives and versions: manuscripts, editing and genetic criticism", "作品并不总有唯一稳定文本。删改、手稿、版本差异和编辑决策记录写作过程；研究者必须区分作者修改、排印错误、审查与后世规范化，并公开采用哪个底本。", "A work does not always have one stable text. Revisions, manuscripts, variants and editorial decisions record its making; researchers distinguish authorial change, printing error, censorship and later normalization, and disclose the copy-text used.", "所谓‘作者最终意图’能否自动决定哪个版本最权威？", "Can an author's supposed final intention automatically determine the authoritative version?", ["lit-gutenberg", "lit-fiction"]),
  m("lit-l5-1", "literature", "L5", "经典形成：教育、奖项与阅读制度", "Canon formation: education, prizes and institutions of reading", "经典不是质量排序的自然结果。课程、翻译、奖项、出版资本和保存条件共同决定哪些作品持续可见；研究既要评价形式成就，也要分析缺席、再发现与制度筛选。", "A canon is not a natural ranking of quality. Curricula, translation, prizes, publishing capital and preservation shape continued visibility; research evaluates form while analyzing absence, rediscovery and institutional selection.", "扩大经典应以增补作品为主，还是改变评价标准与课程结构？", "Should canon expansion mainly add works or change evaluative standards and curricular structures?", ["lit-world", "lit-fiction"]),
  m("lit-l5-2", "literature", "L5", "书籍史与媒介：从卷轴到平台", "Book history and media: from scroll to platform", "文学意义受载体、版式、发行和阅读技术塑造。连载小说、廉价平装、电子书与平台写作拥有不同节奏、受众反馈和所有权结构；媒介条件不是作品之外的背景。", "Literary meaning is shaped by carrier, layout, distribution and reading technology. Serialization, paperbacks, ebooks and platforms create different rhythms, feedback loops and ownership structures; medium is not external background.", "平台按互动数据改变连载情节时，作者与读者的边界在哪里？", "When platforms reshape serial plots through engagement data, where is the boundary between author and reader?", ["lit-fiction", "lit-gutenberg"]),
  m("lit-l5-3", "literature", "L5", "数字人文：语料、远读与尺度", "Digital humanities: corpora, distant reading and scale", "远读用语料统计观察个别阅读难以发现的模式，但语料选择、OCR 错误、分类标签和可视化尺度都会制造结论。计算模式必须返回文本细读检验，不能把频率直接当意义。", "Distant reading uses corpus statistics to reveal patterns invisible to individual reading, but selection, OCR error, labels and visualization scale manufacture results. Computational patterns must return to close reading; frequency is not meaning.", "一个词频趋势何时构成文学史证据，何时只是数字化偏差？", "When is a word-frequency trend literary-historical evidence rather than a digitization artifact?", ["lit-gutenberg", "lit-world"]),
  m("lit-l6-1", "literature", "L6", "原创批评：问题、论点与反证", "Original criticism: question, thesis and counterevidence", "专家论文从可回答而有争议的问题出发，提出能被文本证据修正的论点。必须重建最强竞争性解释、处理不利段落，并说明结论的作品范围、语言范围和历史范围。", "Expert criticism begins with an answerable contested question and a thesis corrigible by textual evidence. It reconstructs the strongest rival reading, handles adverse passages and states textual, linguistic and historical scope.", "如果一篇论文无法说明什么证据会推翻自己，它还是文学论证吗？", "If an essay cannot state what evidence would defeat it, is it still literary argument?", ["lit-fiction", "lit-world", "phil-sep"]),
  m("lit-l6-2", "literature", "L6", "翻译实践：评注、伦理与编辑决策", "Translation practice: commentary, ethics and editorial decisions", "专家翻译同时提交译文与决策说明：叙述声音、语域、文化负载词、节奏和歧义如何处理。译者既不能隐身，也不能用个人解释抹去原作的不确定性。", "Expert translation pairs a text with a rationale for voice, register, culture-bound terms, rhythm and ambiguity. The translator neither disappears nor erases uncertainty through personal interpretation.", "何时应保留陌生感，何时应为目标读者增加解释？", "When should a translation preserve strangeness, and when should it explain for target readers?", ["lit-world", "lit-gutenberg"]),
  m("lit-l6-3", "literature", "L6", "公共批评：面向不同读者解释复杂作品", "Public criticism: explaining complex works to different audiences", "公共写作需要在准确、可读和诚实不确定之间平衡。专家应区分摘要、解释与评价，避免用情节复述代替分析，也不把理论术语当作权威装饰。", "Public criticism balances accuracy, readability and honest uncertainty. Experts distinguish summary, interpretation and evaluation, avoid replacing analysis with plot recap, and never use theory as decorative authority.", "如何向初学者解释复杂理论而不把争议伪装成定论？", "How can complex theory be explained to beginners without presenting disputes as settled fact?", ["lit-world", "lit-fiction"]),

  m("econ-l4-1", "economics", "L4", "微观建模：偏好、约束与均衡", "Microeconomic modeling: preferences, constraints and equilibrium", "微观模型把选择者、可行集合、目标与互动规则写成可检查结构。理性假设是分析工具而非人格判断；比较静态结论必须说明哪些参数改变、哪些制度保持不变。", "Micro models make agents, feasible sets, objectives and rules inspectable. Rationality is an analytical device, not a personality judgment; comparative statics must state which parameters change and which institutions remain fixed.", "放松一个约束总会改善福利吗？如果其他市场同时变化呢？", "Does relaxing a constraint always improve welfare when other markets change too?", ["econ-openstax", "econ-core"]),
  m("econ-l4-2", "economics", "L4", "国民账户：GDP、价格与资产负债表", "National accounts: GDP, prices and balance sheets", "GDP 衡量一定时期内最终生产，不等于财富、福利或生态可持续性。研究要把名义与实际、流量与存量、国内与国民口径分开，并用部门资产负债表追踪风险转移。", "GDP measures final production over a period, not wealth, welfare or ecological sustainability. Analysis separates nominal from real, flow from stock and domestic from national concepts, and uses sectoral balance sheets to track risk transfer.", "经济增长但家庭净资产下降，两个统计可以同时真实吗？", "Can output grow while household net worth falls, with both statistics correct?", ["econ-openstax", "econ-core"]),
  m("econ-l4-3", "economics", "L4", "计量经济学：识别、反事实与因果", "Econometrics: identification, counterfactuals and causality", "因果推断需要说明未发生政策时会怎样。随机试验、自然实验、工具变量和差分方法依赖不同识别假设；显著性不能替代效应大小、机制、外部效度与稳健性。", "Causal inference asks what would have happened without treatment. Experiments, natural experiments, instruments and difference designs rely on different identifying assumptions; significance does not replace effect size, mechanism, external validity or robustness.", "一项政策前后指标改善，为什么仍不能断言政策有效？", "Why can improvement before and after a policy fail to establish effectiveness?", ["econ-core", "econ-openstax"]),
  m("econ-l5-1", "economics", "L5", "产业组织：市场权力、平台与监管", "Industrial organization: market power, platforms and regulation", "市场权力不仅表现为高价格，也可能表现为质量下降、创新受限、劳动议价削弱或数据锁定。双边平台需要同时分析网络效应、多归属、补贴侧与进入壁垒。", "Market power appears not only in prices but in quality, innovation, labor bargaining and data lock-in. Two-sided platforms require analysis of network effects, multi-homing, subsidized sides and entry barriers.", "免费平台如何行使市场权力，监管应测量什么？", "How can a free platform exercise market power, and what should regulators measure?", ["econ-core", "econ-openstax"]),
  m("econ-l5-2", "economics", "L5", "劳动经济学：工资、制度与不平等", "Labor economics: wages, institutions and inequality", "工资由生产率、议价、制度、歧视、分工与宏观需求共同塑造。平均差距不能直接证明单一原因；研究需分解构成、检查选择偏差，并说明无酬照护与非正规劳动。", "Wages reflect productivity, bargaining, institutions, discrimination, task division and aggregate demand. Mean gaps do not prove one cause; research decomposes composition, checks selection and includes unpaid care and informal work.", "同工同酬指标改善时，哪些结构性不平等仍可能被隐藏？", "Which structural inequalities can remain hidden when equal-pay measures improve?", ["econ-core", "econ-openstax"]),
  m("econ-l5-3", "economics", "L5", "发展与环境：增长、能力和行星边界", "Development and environment: growth, capabilities and planetary boundaries", "发展不能只用人均收入衡量，还涉及健康、教育、能力、分配与生态风险。环境政策比较税、总量管制、标准和公共投资，并检查碳泄漏、正义转型与代际负担。", "Development exceeds income per person and includes health, education, capabilities, distribution and ecological risk. Environmental policy compares taxes, caps, standards and public investment while examining leakage, just transition and intergenerational burden.", "低收入地区为何可能合理地拒绝由高收入地区设定的单一减排路径？", "Why might lower-income regions reasonably reject one decarbonization path set by richer regions?", ["econ-core", "econ-openstax"]),
  m("econ-l6-1", "economics", "L6", "制度与政治经济：规则如何分配权力", "Institutions and political economy: how rules distribute power", "制度决定谁能进入谈判、执行合同、承担风险和改变规则。制度分析不能把结果归因于文化标签，而要追踪正式法律、非正式规范、组织能力、历史路径与联盟结构。", "Institutions determine who enters bargaining, enforces claims, bears risk and changes rules. Analysis replaces cultural labels with formal law, informal norms, organizational capacity, path dependence and coalitions.", "一项低效制度长期存在，是因为认知错误、既得利益还是协调困难？如何区分？", "Does an inefficient institution persist through error, vested interest or coordination failure, and how can we tell?", ["econ-core", "econ-openstax", "phil-sep"]),
  m("econ-l6-2", "economics", "L6", "政策设计：目标、工具与评估闭环", "Policy design: objectives, instruments and evaluation loops", "专家政策设计把目标函数、约束、分配影响、执行能力和退出条件写清。试点不只是小规模发布，而应预先规定指标、异质效应、失败标准、复审时间与数据治理。", "Expert policy design specifies objectives, constraints, distribution, implementation capacity and exit conditions. A pilot pre-registers metrics, heterogeneous effects, failure criteria, review timing and data governance rather than merely launching small.", "政策在平均意义上有效，但伤害最脆弱群体时，应怎样修改评价标准？", "How should evaluation change when a policy works on average but harms the most vulnerable?", ["econ-core", "econ-openstax"]),
  m("econ-l6-3", "economics", "L6", "可复现经济研究：数据、代码与模型不确定性", "Reproducible economic research: data, code and model uncertainty", "可复现研究记录数据来源、清洗、估计选择和排除规则，并报告替代模型与不确定性。复现不是机械得到同一数字，还包括检验结论是否依赖脆弱假设。", "Reproducible research records provenance, cleaning, estimation and exclusion rules and reports alternative models and uncertainty. Replication is not merely reproducing a number but testing dependence on fragile assumptions.", "当多个合理模型得出不同政策结论时，专家应如何沟通？", "How should experts communicate when several reasonable models imply different policies?", ["econ-core", "econ-openstax"]),

  m("psych-l4-1", "psychology", "L4", "心理测量：信度、效度与测量等值", "Psychometrics: reliability, validity and invariance", "量表分数不是心理属性本身。信度关乎误差一致性，效度关乎分数解释是否得到证据支持；跨群体比较还需检验题目和结构是否具有测量等值。", "A scale score is not the psychological attribute itself. Reliability concerns error consistency, validity concerns evidence for score interpretation, and group comparison requires measurement invariance across items and structure.", "一个量表在两个群体中同样可靠，为什么仍可能不能比较均值？", "Why can equally reliable scales still fail to support mean comparison across groups?", ["psych-openstax", "psych-noba"]),
  m("psych-l4-2", "psychology", "L4", "实验设计：功效、预注册与多重比较", "Experimental design: power, preregistration and multiplicity", "研究设计应在收集数据前明确假设、主要指标、样本量和排除规则。低功效不仅增加漏检，也会放大已发表效应；多重比较需要透明校正和探索性标记。", "Design specifies hypotheses, primary outcomes, sample size and exclusions before data collection. Low power raises false negatives and inflates published effects; multiple testing requires transparent correction and exploratory labeling.", "预注册会限制创造力，还是把探索与验证区分得更诚实？", "Does preregistration constrain creativity or honestly separate exploration from confirmation?", ["psych-openstax", "psych-noba"]),
  m("psych-l4-3", "psychology", "L4", "认知神经方法：定位、网络与反向推断", "Cognitive neuroscience: localization, networks and reverse inference", "脑成像和电生理测量是神经活动的间接指标。区域激活不等于某心理过程被证明；反向推断、时间分辨率、任务设计和多变量模式共同限定解释。", "Imaging and electrophysiology are indirect measures. Regional activation does not prove a psychological process; reverse inference, temporal resolution, task design and multivariate patterns constrain interpretation.", "看到杏仁核激活，为什么不能直接断言参与者感到恐惧？", "Why does amygdala activation not by itself establish that a participant feels fear?", ["psych-openstax", "psych-noba"]),
  m("psych-l5-1", "psychology", "L5", "心理分类：维度、诊断与文化边界", "Psychological classification: dimensions, diagnosis and culture", "诊断分类服务沟通、研究和资源配置，但类别边界会受阈值、文化与制度影响。研究应区分症状维度、功能损害、病因假说与临床决策，避免把标签当本质。", "Diagnostic classification supports communication, research and allocation, but boundaries depend on thresholds, culture and institutions. Analysis separates symptom dimensions, impairment, etiological hypotheses and decisions rather than treating labels as essences.", "诊断标签何时帮助获得支持，何时会缩窄对个人的理解？", "When does a diagnosis enable support, and when does it narrow understanding of a person?", ["psych-openstax", "psych-noba"]),
  m("psych-l5-2", "psychology", "L5", "文化与发展：普遍机制还是情境路径", "Culture and development: universal mechanisms or situated pathways", "发展研究不能把一个社会的年龄规范当作普遍阶段。照护制度、语言、教育、经济压力与历史经验共同塑造发展路径；跨文化比较要避免缺陷模型和测量不等值。", "Developmental research cannot universalize one society's age norms. Care systems, language, schooling, economic pressure and history shape pathways; comparison avoids deficit models and non-equivalent measurement.", "同一行为在不同文化中承担不同功能时，还能用同一发展量表吗？", "Can one developmental scale be used when the same behavior serves different cultural functions?", ["psych-noba", "psych-openstax"]),
  m("psych-l5-3", "psychology", "L5", "计算心理学：模型比较与可解释行为", "Computational psychology: model comparison and interpretable behavior", "计算模型把学习、决策或记忆假说转成可拟合预测。参数有心理意义之前，必须证明可识别、能与替代模型区分，并经后验预测和新数据检验。", "Computational models turn hypotheses about learning, choice or memory into fitted predictions. Parameters gain psychological meaning only after identifiability, model comparison, posterior prediction and testing on new data.", "一个模型预测准确但参数无法稳定恢复，能解释心理机制吗？", "Can a predictively accurate model explain mechanism if its parameters cannot be recovered?", ["psych-noba", "science-algorithms"]),
  m("psych-l6-1", "psychology", "L6", "元分析与证据综合：异质性和发表偏差", "Meta-analysis and evidence synthesis: heterogeneity and publication bias", "元分析不是把研究数量相加，而是比较效应、精度、设计和情境。总体均值可能遮蔽真实异质性；研究者要检查选择性发表、依赖效应与结论对模型的敏感性。", "Meta-analysis compares effects, precision, design and context rather than counting studies. A pooled mean can hide real heterogeneity; synthesis checks selective publication, dependent effects and model sensitivity.", "平均效应很小但某些群体受益显著时，应如何作结论？", "How should one conclude when the average effect is small but some groups benefit substantially?", ["psych-noba", "psych-openstax"]),
  m("psych-l6-2", "psychology", "L6", "干预伦理：效果、伤害与知情选择", "Intervention ethics: benefit, harm and informed choice", "干预评价同时考虑效果、可及性、替代方案、副作用、污名和权力关系。研究证据不能替代个体知情选择；高风险情境还需明确转介和专业资格边界。", "Intervention evaluation includes benefit, access, alternatives, adverse effects, stigma and power. Evidence does not replace informed choice, and high-risk contexts require referral and professional-scope boundaries.", "统计上有效的干预何时仍不应向某个群体推广？", "When should a statistically effective intervention still not be promoted to a group?", ["psych-openstax", "psych-noba"]),
  m("psych-l6-3", "psychology", "L6", "独立研究：从理论构念到开放材料", "Independent research: from construct to open materials", "专家研究把理论构念转化为可审计操作，预先说明样本、测量、分析与伦理，公开材料和限制。高质量结论区分观察、模型推断与实践建议。", "Expert research turns constructs into auditable operations, pre-specifies sampling, measurement, analysis and ethics, and opens materials and limitations. Conclusions distinguish observation, model inference and practice recommendation.", "怎样设计一个既能被复现、又尊重参与者隐私的开放研究？", "How can research be reproducible while protecting participant privacy?", ["psych-noba", "psych-openstax"]),

  m("biz-l4-1", "business", "L4", "财务阅读：现金流、单位经济与情景", "Financial reading: cash flow, unit economics and scenarios", "收入增长不等于价值创造。分析要连接利润表、现金流和资产负债表，检查获客成本、留存、贡献毛利、营运资本与融资假设，并用情景而非单点预测。", "Revenue growth is not value creation. Analysis connects income, cash flow and balance sheet; tests acquisition cost, retention, contribution margin, working capital and financing; and uses scenarios rather than point forecasts.", "单位经济为正的公司为什么仍可能因增长而破产？", "Why can a firm with positive unit economics still fail because it grows?", ["business-management", "business-org"]),
  m("biz-l4-2", "business", "L4", "运营与供应链：流动、瓶颈和韧性", "Operations and supply chains: flow, bottlenecks and resilience", "运营系统要看需求变异、库存、等待、产能和质量之间的关系。局部效率可能把风险推向供应商或客户；韧性设计比较冗余、多源、可见性与恢复时间。", "Operations links demand variation, inventory, waiting, capacity and quality. Local efficiency can export risk to suppliers or customers; resilience compares redundancy, multi-sourcing, visibility and recovery time.", "把库存降到最低何时会增加全系统成本？", "When does minimizing inventory raise total system cost?", ["business-management", "business-org"]),
  m("biz-l4-3", "business", "L4", "市场研究：需求、分群与证据质量", "Market research: demand, segmentation and evidence quality", "市场研究把受访偏好与真实行为区分开，结合访谈、观察、实验和交易数据。分群必须能解释差异并指导行动，不能只是漂亮的人物画像。", "Market research separates stated preference from behavior and combines interviews, observation, experiments and transaction data. Segments must explain differences and guide action rather than decorate personas.", "用户说喜欢一个功能却从不使用，团队应相信哪种证据？", "When users praise a feature but never use it, which evidence should the team trust?", ["business-writing", "business-management"]),
  m("biz-l5-1", "business", "L5", "竞争战略：能力、定位与动态反应", "Competitive strategy: capabilities, positioning and dynamics", "战略不是愿望清单，而是对客户、活动系统、取舍与竞争反应的连贯选择。资源优势只有在稀缺、难复制且组织能利用时才可能持续。", "Strategy is not a wish list but a coherent choice about customers, activities, trade-offs and competitive response. A resource advantage persists only when scarce, hard to imitate and organizationally usable.", "竞争者复制了产品功能，哪些系统能力仍可能保持差异？", "If rivals copy product features, which system capabilities can preserve differentiation?", ["business-management", "business-org"]),
  m("biz-l5-2", "business", "L5", "组织设计：激励、信息与决策权", "Organization design: incentives, information and decision rights", "组织图只显示汇报线，不显示信息流、非正式权力和实际决策。设计要让决策权靠近知识，同时设置升级机制、问责边界和跨部门接口。", "An org chart shows reporting lines, not information flow, informal power or actual decisions. Design moves authority toward knowledge while creating escalation, accountability and cross-functional interfaces.", "授权增加后错误也增加，应该收回权力还是改善反馈系统？", "When empowerment increases errors, should authority be recentralized or feedback improved?", ["business-org", "business-management"]),
  m("biz-l5-3", "business", "L5", "公司治理：董事会、利益相关者与伦理", "Corporate governance: boards, stakeholders and ethics", "治理决定谁监督管理层、谁获得信息、谁能申诉以及长期风险如何进入决策。合规是最低线，伦理分析还要处理合法但不公平的商业模式和外部成本。", "Governance determines who oversees management, receives information, appeals and brings long-term risk into decisions. Compliance is a floor; ethics addresses legal but unfair models and external costs.", "董事会何时应拒绝短期有利但长期损害信任的方案？", "When should a board reject a short-term gain that erodes long-term trust?", ["business-org", "business-management", "phil-sep"]),
  m("biz-l6-1", "business", "L6", "跨境转型：制度、文化与实施组合", "Cross-border transformation: institutions, culture and implementation", "跨境变革必须同时处理法律、劳动制度、语言、客户规范与本地能力。总部模板只是初始假设；实施组合要区分不可妥协原则、可本地化流程和共同学习机制。", "Cross-border change addresses law, labor institutions, language, customer norms and local capability. Headquarters templates are hypotheses; implementation separates non-negotiable principles, localizable processes and mutual learning.", "全球一致性与本地自主冲突时，哪些层级应该统一？", "When global consistency conflicts with local autonomy, which layers should be standardized?", ["business-org", "business-writing", "daily-cefr"]),
  m("biz-l6-2", "business", "L6", "情景规划：不确定性、信号与战略选择", "Scenario planning: uncertainty, signals and strategic options", "情景不是预测多个数字，而是用关键不确定性构造连贯未来，测试战略在不同世界中的脆弱点。每个情景需要先行指标、触发条件和可逆选项。", "Scenarios are not several forecasts but coherent futures built from critical uncertainties to test strategic fragility. Each needs leading indicators, triggers and reversible options.", "如果团队只选择最可能情景，情景规划还剩下什么价值？", "If a team chooses only the most likely scenario, what value remains in scenario planning?", ["business-management", "business-org"]),
  m("biz-l6-3", "business", "L6", "高层决策项目：论证、异议与复盘", "Executive decision project: argument, dissent and review", "专家级决策包包含问题定义、选项、证据质量、财务与非财务影响、最强异议、决策人和复审机制。复盘评价当时过程而不只看事后结果。", "An expert decision pack includes problem definition, options, evidence quality, financial and non-financial effects, strongest dissent, owner and review mechanism. Postmortem evaluates process at the time, not only outcome in hindsight.", "一个坏结果能否来自好决策？应如何复盘而不产生结果偏见？", "Can a bad outcome follow a good decision, and how can review avoid outcome bias?", ["business-writing", "business-management", "business-org"]),

  m("daily-l4-1", "daily", "L4", "公共服务语言：权利、程序与书面记录", "Public-service language: rights, procedures and records", "独立生活需要读懂资格条件、截止日期、申诉渠道和证据要求。与机构沟通时要区分询问、正式申请与异议，并保留编号、日期和书面确认；课程不替代法律建议。", "Independent living requires reading eligibility, deadlines, appeal routes and evidence requirements. Institutional communication distinguishes inquiry, application and objection and preserves reference numbers, dates and written confirmation; this is not legal advice.", "工作人员口头承诺与书面规则冲突时，怎样礼貌而有效地确认？", "How can you verify politely and effectively when an oral assurance conflicts with written rules?", ["daily-eu", "daily-cefr"]),
  m("daily-l4-2", "daily", "L4", "高级职场语言：提案、异议与边界", "Advanced workplace language: proposals, dissent and boundaries", "职场熟练度不仅是礼貌，还要能提出有证据的异议、协商工作量、确认责任并拒绝不安全要求。语言选择应匹配权力差距、书面记录需要和关系修复。", "Workplace proficiency includes evidence-based dissent, workload negotiation, accountability and refusal of unsafe requests. Language must match power distance, documentation needs and relationship repair.", "怎样不同意主管，同时把问题从个人冲突转化为可检验风险？", "How can you disagree with a manager while turning personal conflict into a testable risk?", ["daily-cefr", "business-writing"]),
  m("daily-l4-3", "daily", "L4", "新闻与媒体理解：事实、立场和来源", "News and media literacy: fact, framing and source", "高级阅读要分开事件、引语、记者推断、标题框架和评论。比较多语报道时还要检查机构名称、数字口径、时区与译词如何改变责任和确定性。", "Advanced reading separates event, quotation, reporter inference, headline framing and opinion. Multilingual comparison checks institutions, denominators, time zones and translations that alter agency and certainty.", "两篇报道事实相同却结论相反，应先比较哪些语言结构？", "When two reports share facts but imply opposite conclusions, which language structures should be compared first?", ["daily-cefr", "daily-eu"]),
  m("daily-l5-1", "daily", "L5", "语域与变体：标准语、方言和身份", "Register and variation: standards, dialects and identity", "精通者能识别正式、口语、地区、代际与职业变体，却不把标准语等同于更聪明。选择语域是参与关系的行动，也受歧视、身份与可理解性约束。", "Proficient users recognize formal, colloquial, regional, generational and professional variation without equating standards with intelligence. Register choice participates in relationships and is constrained by discrimination, identity and intelligibility.", "求职时调整口音是策略、压力还是身份损失？答案取决于什么？", "Is accent adjustment in a job interview strategy, pressure or identity loss, and what determines the answer?", ["daily-cefr", "daily-wikivoyage"]),
  m("daily-l5-2", "daily", "L5", "幽默、反讽与隐含意义", "Humor, irony and implied meaning", "幽默依赖共享脚本、时机、语调和安全关系。反讽常用表面肯定表达批评，但跨文化和文字沟通容易失去线索；精通不等于模仿所有笑话，而是判断风险和修复误读。", "Humor depends on shared scripts, timing, prosody and safe relationships. Irony may criticize through surface praise but loses cues across cultures and text; proficiency means judging risk and repairing misunderstanding, not copying every joke.", "为什么语法完全理解后，笑点仍可能无法翻译？", "Why can a joke remain untranslatable after every grammatical element is understood?", ["daily-cefr", "daily-wikivoyage"]),
  m("daily-l5-3", "daily", "L5", "冲突调解：复述、利益与修复", "Conflict mediation: reframing, interests and repair", "调解语言把指责重述为可讨论的观察、需要和请求，并检查双方是否认可重述。调解者不能制造虚假对称，也不能在安全、骚扰或权利问题上用妥协掩盖责任。", "Mediation reframes accusation into discussable observations, needs and requests and checks whether parties accept the reframing. It must not create false symmetry or hide responsibility in safety, harassment or rights cases.", "什么时候‘双方都有责任’是一种不准确而有害的翻译？", "When is both sides are responsible an inaccurate and harmful translation?", ["daily-cefr", "business-writing"]),
  m("daily-l6-1", "daily", "L6", "多语主持：议程、轮次与共同理解", "Plurilingual facilitation: agenda, turns and shared understanding", "专家主持能设定目的、时间和决策规则，邀请低权力成员发言，阶段性总结，并把术语差异显性化。理解检查不能只问‘明白吗’，而要让参与者复述行动与风险。", "Expert facilitation sets purpose, time and decision rules, invites lower-power voices, summarizes stages and surfaces terminological differences. It verifies understanding through restated actions and risks, not merely asking if everyone understands.", "如何设计会议规则，让语言能力较弱者仍能影响决定？", "How can meeting rules let less fluent participants still shape decisions?", ["daily-cefr", "business-writing"]),
  m("daily-l6-2", "daily", "L6", "公共表达：证据、故事与问答", "Public speaking: evidence, narrative and questions", "专家表达根据听众知识调整结构，但不降低证据标准。开场建立问题，主体连接主张与证据，结尾明确行动；问答中应区分不知道、不同意和问题前提错误。", "Expert speaking adjusts structure to audience knowledge without lowering evidence standards. Openings frame problems, bodies connect claims and evidence, conclusions clarify action, and Q&A distinguishes not knowing, disagreement and false premises.", "怎样用三分钟解释复杂政策，同时诚实保留不确定性？", "How can a complex policy be explained in three minutes while preserving uncertainty honestly?", ["daily-cefr", "daily-eu"]),
  m("daily-l6-3", "daily", "L6", "自主多语生活档案：能力、风险与持续学习", "Autonomous plurilingual portfolio: capability, risk and lifelong learning", "专家学习者用真实任务档案证明能力：合同、演讲、申诉、医疗沟通和文化调解。档案同时记录错误、修复与下一步，不把考试等级当作所有场景的永久通行证。", "Expert learners evidence capability through authentic tasks: contracts, talks, appeals, healthcare communication and mediation. Portfolios record error, repair and next steps rather than treating a test level as permanent universal clearance.", "哪些高风险任务即使语言流利也应寻求专业翻译或法律医疗帮助？", "Which high-risk tasks still require professional interpreting, legal or medical help despite fluency?", ["daily-cefr", "daily-eu"]),

  m("art-l4-1", "art", "L4", "技术艺术史：材料、检测与保存", "Technical art history: materials, imaging and conservation", "技术艺术史结合颜料、底层、制作痕迹、成像与保存记录研究作品生命史。科学检测不会自动给出作者或意义，数据必须与来源、工作室实践和修复史共同解释。", "Technical art history combines pigments, underlayers, making traces, imaging and conservation records. Scientific tests do not automatically determine authorship or meaning; data must meet provenance, workshop practice and treatment history.", "检测发现后期颜料时，如何区分修复、改作与伪造？", "When later pigment is detected, how can conservation, alteration and forgery be distinguished?", ["art-met", "art-smarthistory", "science-physics"]),
  m("art-l4-2", "art", "L4", "摄影与电影：取景、时间和观看者", "Photography and film: framing, time and spectatorship", "镜头图像不是现实的中性切片。焦距、取景、曝光、剪辑、声音和传播语境组织因果与情感；分析还要区分索引痕迹、摆拍、合成与纪录伦理。", "Lens images are not neutral slices of reality. Focal length, framing, exposure, editing, sound and circulation organize causality and emotion; analysis separates indexical trace, staging, compositing and documentary ethics.", "一张未经修改的照片为什么仍可能高度误导？", "Why can an unaltered photograph still be highly misleading?", ["art-smarthistory", "art-met"]),
  m("art-l4-3", "art", "L4", "建筑与设计：空间、身体和使用", "Architecture and design: space, bodies and use", "建筑分析同时考察结构、材料、动线、尺度、气候、法规与社会使用。图纸中的理想空间会被维护、无障碍、产权和日常实践重新定义。", "Architectural analysis joins structure, material, circulation, scale, climate, regulation and social use. Ideal space on drawings is redefined by maintenance, accessibility, ownership and everyday practice.", "一座形式创新但排斥部分身体的建筑能否称为成功？", "Can a formally innovative building be successful if it excludes some bodies?", ["art-met", "art-smarthistory"]),
  m("art-l5-1", "art", "L5", "性别、凝视与再现政治", "Gender, the gaze and politics of representation", "凝视理论研究观看位置、欲望、权力和被观看者的能动性，不等于给艺术家贴道德标签。研究需要结合构图、委托、展示、观众和反向观看策略。", "Theories of the gaze study viewing position, desire, power and agency of the viewed rather than morally labeling artists. Analysis joins composition, commission, display, audience and counter-gazes.", "作品批判对象化时，是否仍可能在视觉上复制对象化？", "Can a work visually reproduce objectification while attempting to criticize it?", ["art-smarthistory", "art-met", "phil-sep"]),
  m("art-l5-2", "art", "L5", "全球现代主义：多中心、翻译与不同时性", "Global modernisms: multiple centers, translation and uneven time", "现代主义不是欧洲创新向外扩散的单线故事。艺术家在殖民、民族国家、城市化和本地传统中主动改写形式；比较应追踪网络与权力，而非用‘迟到’描述差异。", "Modernism is not a one-way diffusion of European innovation. Artists actively reworked form through colonialism, nationhood, urbanization and local tradition; comparison traces networks and power rather than labeling difference belated.", "当一个形式在不同城市承担相反政治意义时，还能归入同一流派吗？", "Can one form belong to the same movement when it bears opposite politics in different cities?", ["art-smarthistory", "art-met"]),
  m("art-l5-3", "art", "L5", "数字与生成艺术：代码、版本和作者性", "Digital and generative art: code, versions and authorship", "数字作品可能由代码、数据、界面、执行环境和观众互动共同构成。保存需要记录依赖与版本；作者性分析要区分概念、系统设计、训练材料、执行选择和平台权力。", "Digital works may comprise code, data, interface, runtime and audience interaction. Preservation records dependencies and versions; authorship distinguishes concept, system design, training material, execution choices and platform power.", "每次运行结果不同的作品，其‘原作’究竟是什么？", "What is the original of a work that changes on every execution?", ["art-smarthistory", "science-algorithms", "phil-sep"]),
  m("art-l6-1", "art", "L6", "来源与归还：证据链、所有权和修复正义", "Provenance and restitution: evidence chains, ownership and repair", "来源研究重建对象从制作到收藏的转移，区分合法所有权、伦理正当性与信息缺口。专家报告应标记战争、殖民、强迫交易和可疑空白，并呈现不同申索者的证据。", "Provenance reconstructs transfer from making to collection and separates legal title, ethical legitimacy and informational gaps. Expert reports flag war, colonial extraction, coercive sale and suspicious absence while presenting rival claims.", "缺少完整文件时，谁应承担证明合法取得的责任？", "Who bears the burden of proving legitimate acquisition when records are incomplete?", ["art-met", "art-smarthistory"]),
  m("art-l6-2", "art", "L6", "策展实验室：选择、空间与公共叙事", "Curatorial laboratory: selection, space and public narrative", "策展用选择、邻接、动线、文字、灯光与无障碍设计形成论证。展览必须说明缺席与借展限制，区分教育性简化和历史扭曲，并为观众提供多种进入路径。", "Curation argues through selection, adjacency, circulation, text, light and accessibility. Exhibitions disclose absence and loan constraints, distinguish pedagogic simplification from distortion and offer multiple entry paths.", "如何策划一场不以单一文明中心组织世界艺术的展览？", "How can an exhibition of world art avoid organization around one civilizational center?", ["art-met", "art-smarthistory"]),
  m("art-l6-3", "art", "L6", "独立艺术史研究：对象、方法与目录条目", "Independent art-historical research: object, method and catalogue entry", "专家研究从对象的可见和物质问题出发，结合档案、比较、技术证据与理论。目录条目应区分已知、归属、争议和推论，并让读者追踪每个关键判断的来源。", "Expert research begins with visible and material questions and combines archive, comparison, technical evidence and theory. Catalogue entries separate known fact, attribution, dispute and inference and make key claims traceable.", "一项新的作者归属需要哪些相互独立的证据才能站得住？", "What independent evidence is needed to sustain a new attribution?", ["art-met", "art-smarthistory"]),

  m("phil-l4-1", "philosophy", "L4", "形式逻辑：量化、证明与反模型", "Formal logic: quantification, proof and countermodels", "形式逻辑把论证结构与内容分开，用语法、语义和证明系统检验有效性。量词范围、条件句和模态常造成自然语言歧义；反模型展示前提为真而结论为假的可能结构。", "Formal logic separates structure from content and tests validity through syntax, semantics and proof. Quantifier scope, conditionals and modality create ambiguity; countermodels show a structure where premises hold and conclusion fails.", "为什么一个听起来荒谬的论证仍可能在形式上有效？", "Why can an absurd-sounding argument still be formally valid?", ["phil-iep", "phil-sep"]),
  m("phil-l4-2", "philosophy", "L4", "语言哲学：指称、意义与语用", "Philosophy of language: reference, meaning and pragmatics", "语言哲学区分词指向什么、句子真值如何形成、说话者在情境中做什么。名称、描述、隐喻和言语行为显示意义既不只在词典，也不等于个人意图。", "Philosophy of language distinguishes what words refer to, how sentence truth arises and what speakers do in context. Names, descriptions, metaphor and speech acts show that meaning is neither only dictionary content nor private intention.", "一句话字面为真，却为何仍可能误导或冒犯？", "How can a literally true sentence still mislead or offend?", ["phil-sep", "phil-iep"]),
  m("phil-l4-3", "philosophy", "L4", "伦理论证：案例、原则与反思平衡", "Ethical argument: cases, principles and reflective equilibrium", "伦理分析在个案判断、一般原则与背景理论之间反复校正。思想实验揭示直觉结构，却可能删除历史、制度和身份；反思平衡不是寻找舒适一致，而是公开修正理由。", "Ethical analysis revises cases, principles and background theories against one another. Thought experiments expose intuition but may delete history, institutions and identity; reflective equilibrium makes revision public rather than seeking comfort.", "当原则与可靠案例判断冲突时，哪一方应先修改？", "When a principle conflicts with reliable case judgment, which should be revised first?", ["phil-sep", "phil-iep"]),
  m("phil-l5-1", "philosophy", "L5", "心灵哲学：意识、表征与身体", "Philosophy of mind: consciousness, representation and embodiment", "心灵哲学比较物理主义、功能主义、具身与现象学路径，区分行为能力、信息表征和主观体验。神经相关物不能自动解决解释鸿沟，但第一人称报告也需要方法约束。", "Philosophy of mind compares physicalist, functional, embodied and phenomenological approaches and separates capacity, representation and experience. Neural correlates do not automatically close explanatory gaps, while first-person reports also need discipline.", "一个系统行为上完全像人，是否足以证明它有体验？", "Is human-equivalent behavior sufficient evidence of experience?", ["phil-sep", "phil-iep", "psych-noba"]),
  m("phil-l5-2", "philosophy", "L5", "科学哲学：解释、实在论与模型", "Philosophy of science: explanation, realism and models", "科学哲学研究证据如何支持理论、模型如何代表、解释与预测何时分离。实在论争论不是‘相信科学’与否，而是成功理论对不可观察实体承诺到什么程度。", "Philosophy of science studies evidential support, representation and divergence between explanation and prediction. Realism is not whether to believe science but how far successful theories commit us to unobservables.", "两个模型预测相同却解释不同，经验能否决定选择？", "If two models predict alike but explain differently, can evidence decide between them?", ["phil-sep", "phil-iep", "science-physics"]),
  m("phil-l5-3", "philosophy", "L5", "政治哲学：正义、权力与结构", "Political philosophy: justice, power and structure", "政治哲学比较分配、权利、承认、民主和非支配等标准。制度表面中立仍可能通过历史起点与执行差异产生结构性结果；分析需区分正当性、合法性和有效性。", "Political philosophy compares distribution, rights, recognition, democracy and non-domination. Formally neutral institutions can create structural outcomes through history and enforcement; analysis separates legitimacy, legality and effectiveness.", "规则对所有人相同，为什么结果仍可能不公正？", "Why can identical rules for everyone still produce injustice?", ["phil-sep", "phil-iep"]),
  m("phil-l6-1", "philosophy", "L6", "比较哲学：概念翻译与不可公度", "Comparative philosophy: conceptual translation and incommensurability", "比较哲学不能用一个传统的问题预先裁剪另一个传统。专家需要重建术语在文本、实践和争论中的功能，再比较可译、部分可译和改变问题框架的概念。", "Comparative philosophy must not trim one tradition to another's questions. Experts reconstruct concepts in text, practice and debate before comparing translatable, partially translatable and framework-changing terms.", "没有一一对应词时，比较是失败还是哲学发现的开始？", "When no one-to-one term exists, is comparison failing or beginning philosophical discovery?", ["phil-sep", "phil-iep"]),
  m("phil-l6-2", "philosophy", "L6", "原创哲学论文：论题、文献与最强异议", "Original philosophy thesis: problem, literature and strongest objection", "原创论文不是表达个人世界观，而是在现有争论中定位一个缺口，定义术语，给出有效论证并回应最强异议。每个前提都需说明依据与适用范围。", "An original thesis is not a personal worldview but a located gap in existing debate, with defined terms, valid argument and response to the strongest objection. Each premise needs grounds and scope.", "如果反对意见迫使你改变结论，论文是失败还是进步？", "If an objection forces a changed conclusion, is the thesis failing or advancing?", ["phil-sep", "phil-iep"]),
  m("phil-l6-3", "philosophy", "L6", "公共哲学：澄清争议而不制造伪平衡", "Public philosophy: clarifying disputes without false balance", "公共哲学把概念、价值冲突和证据标准说清，又不把所有立场当作同等有据。专家应标记事实争议、规范分歧和语词混淆，并说明自己的不确定性。", "Public philosophy clarifies concepts, value conflict and evidence without treating all positions as equally supported. Experts distinguish factual dispute, normative disagreement and verbal confusion and state uncertainty.", "如何在公共争论中公平呈现反方，却不放大明显虚假主张？", "How can a public argument represent opponents fairly without amplifying demonstrably false claims?", ["phil-sep", "phil-iep"]),

  m("sci-l4-1", "science", "L4", "数学工具：线性代数、微分与概率", "Mathematical tools: linear algebra, calculus and probability", "向量与矩阵描述状态和变换，微分描述局部变化，概率描述不确定结构。方法学习强调量纲、假设和几何意义，而非只记公式；同一符号在不同模型中角色可能不同。", "Vectors and matrices describe states and transformations, calculus local change and probability uncertainty. Methods emphasize dimensions, assumptions and geometry rather than formula recall; one symbol can play different roles across models.", "一个数学推导正确，为什么物理结论仍可能错误？", "Why can a correct derivation still yield a wrong physical conclusion?", ["science-physics", "science-algorithms"]),
  m("sci-l4-2", "science", "L4", "统计推断：估计、区间与模型检查", "Statistical inference: estimation, intervals and model checking", "统计推断把样本与生成过程连接。置信区间、贝叶斯区间和预测区间回答不同问题；模型检查需要残差、校准、敏感性和外部验证，而非只报告一个 p 值。", "Inference links samples to generating processes. Confidence, credible and prediction intervals answer different questions; model checking uses residuals, calibration, sensitivity and external validation rather than one p-value.", "样本量巨大时，极小而无意义的差异为何也会显著？", "Why can huge samples make trivial differences statistically significant?", ["science-algorithms", "psych-openstax"]),
  m("sci-l4-3", "science", "L4", "可复现实验：测量、代码与误差传播", "Reproducible experiments: measurement, code and error propagation", "可复现研究记录仪器、校准、随机化、数据版本、代码环境与排除决定。误差传播把各环节不确定性带入结论；失败复现需要诊断方法差异而非立即判定欺诈。", "Reproducible research records instruments, calibration, randomization, data versions, code environments and exclusions. Error propagation carries uncertainty into conclusions; failed replication diagnoses methodological differences before alleging fraud.", "另一实验室无法复现结果时，最先应检查哪些层级？", "Which layers should be checked first when another lab cannot replicate a result?", ["science-physics", "science-algorithms"]),
  m("sci-l5-1", "science", "L5", "网络安全与密码学：威胁模型和信任边界", "Cybersecurity and cryptography: threat models and trust boundaries", "安全不是添加加密按钮，而是定义资产、攻击者能力、信任边界和失败后果。密码原语可能数学安全却因密钥管理、随机数、实现侧信道或人机界面失效。", "Security begins with assets, adversary capabilities, trust boundaries and failure impact, not an encryption checkbox. Sound primitives fail through key management, randomness, side channels, implementation or interface.", "端到端加密成立时，系统仍可能从哪些位置泄露敏感信息？", "Where can sensitive information leak even when end-to-end encryption holds?", ["science-distributed", "science-algorithms"]),
  m("sci-l5-2", "science", "L5", "生物技术与基因组：关联、编辑和伦理", "Biotechnology and genomics: association, editing and ethics", "基因组关联不等于单基因决定，效应依赖群体、环境与统计模型。基因编辑还涉及脱靶、嵌合、可逆性、知情同意和代际影响；技术可行不等于临床正当。", "Genomic association is not single-gene determination; effects depend on population, environment and model. Editing raises off-target, mosaic, reversibility, consent and intergenerational issues; technical feasibility is not clinical justification.", "治疗性编辑与增强性编辑的边界能否只靠疾病定义划定？", "Can the treatment–enhancement boundary be drawn solely by defining disease?", ["science-algorithms", "phil-sep"]),
  m("sci-l5-3", "science", "L5", "气候与能源系统：反馈、情景和转型", "Climate and energy systems: feedbacks, scenarios and transition", "气候模型耦合辐射、海洋、陆地与社会排放情景；不确定性不等于不知道。能源转型需同时比较全生命周期排放、可靠性、材料、土地、成本和分配。", "Climate models couple radiation, oceans, land and social emission scenarios; uncertainty is not ignorance. Energy transition compares lifecycle emissions, reliability, materials, land, cost and distribution.", "两个低碳方案总减排相近时，哪些系统指标决定选择？", "When two low-carbon paths cut similar emissions, which system indicators should decide?", ["science-physics", "econ-core"]),
  m("sci-l6-1", "science", "L6", "量子信息：纠缠、噪声与纠错", "Quantum information: entanglement, noise and error correction", "量子信息把态、测量与信道转成计算资源。纠缠不允许超光速通信；实际优势受门保真度、退相干、纠错开销、算法结构和经典基线限制。", "Quantum information treats states, measurements and channels as computational resources. Entanglement does not allow faster-than-light signalling; advantage depends on fidelity, decoherence, error-correction overhead, algorithm structure and classical baselines.", "量子算法理论加速很大，为什么短期设备仍可能没有实用优势？", "Why can a theoretically fast quantum algorithm lack practical advantage on near-term hardware?", ["science-quantum", "science-physics"]),
  m("sci-l6-2", "science", "L6", "AI 系统工程：数据、评估与安全论证", "AI systems engineering: data, evaluation and safety cases", "AI 产品是数据管线、模型、工具、权限、监控和人员流程的系统。专家评估覆盖分布偏移、滥用、校准、隐私、回退和事故响应，并为高风险部署建立可审计安全论证。", "An AI product is a system of data pipelines, models, tools, permissions, monitoring and people. Expert evaluation covers shift, misuse, calibration, privacy, fallback and incident response and builds auditable safety cases for high-risk deployment.", "离线基准优秀的模型，部署前还必须通过哪些系统级测试？", "Which system-level tests remain necessary when a model excels on offline benchmarks?", ["science-dl", "science-distributed", "phil-sep"]),
  m("sci-l6-3", "science", "L6", "研究架构项目：问题、证据与负责任发布", "Research architecture project: question, evidence and responsible release", "专家项目从可证伪问题出发，选择模型、实验、数据和复现方案，预先处理安全、许可、隐私与双重用途。发布不仅包括结果，还包括限制、失败模式和监测计划。", "An expert project begins with a falsifiable question and chooses models, experiments, data and replication while addressing safety, licensing, privacy and dual use. Release includes limits, failure modes and monitoring, not results alone.", "什么时候开放全部代码和数据会与负责任研究发生冲突？", "When can releasing all code and data conflict with responsible research?", ["science-algorithms", "science-dl", "science-distributed"]),
];

const STAGE_COPY = {
  L1: {
    zh: "基础阶段先建立可操作定义，学会区分相邻概念，并用一个可观察例子检验理解。",
    en: "At foundation level, build an operational definition, distinguish neighboring concepts and test understanding with an observable example.",
  },
  L2: {
    zh: "核心阶段追踪机制、证据与边界条件；同一个术语在不同框架中可能承担不同功能。",
    en: "At core level, trace mechanisms, evidence and boundary conditions; the same term may play different roles across frameworks.",
  },
  L3: {
    zh: "高阶阶段比较竞争性解释，暴露隐藏假设，并把概念连接到研究争议、伦理与方法限制。",
    en: "At advanced level, compare rival explanations, expose hidden assumptions and connect the concept to research disputes, ethics and methodological limits.",
  },
  L4: {
    zh: "方法阶段训练可复用的分析工具：提出问题、选择材料、说明方法，并让证据能够反驳自己的判断。",
    en: "At methods level, practice reusable analytical tools: frame a question, select material, justify a method and let evidence challenge your judgment.",
  },
  L5: {
    zh: "研究阶段进入专业争论，比较文献、数据与理论框架，识别尚未解决的问题以及研究设计的代价。",
    en: "At research level, enter specialist debates, compare literature, data and frameworks, and identify unresolved questions and design trade-offs.",
  },
  L6: {
    zh: "专家综合阶段要求形成可辩护的原创立场，整合跨学科证据，回应最强反对意见，并向不同公众清楚表达。",
    en: "At expert-synthesis level, form a defensible original position, integrate cross-disciplinary evidence, answer the strongest objections and communicate to different publics.",
  },
};

const SUBJECT_TERMS: Record<SubjectId, string> = {
  literature: `[[FR: Lire avec précision || lecture rapprochée : 细读 / close reading : groupe nominal féminin；以文本证据约束解释]]\n[[DE: Text und Deutung || Deutung : 解释 / interpretation : Femininum；强调意义建构 ;; Textbeleg : 文本证据 / textual evidence : Maskulinum；Text + Beleg]]\n[[IT: Forma e interpretazione || forma : 形式 / form : nome femminile；dal latino forma ;; interpretazione : 解释 / interpretation : nome femminile]]\n[[ES: Texto y lectura crítica || lectura crítica : 批判性阅读 / critical reading : sintagma nominal femenino ;; evidencia textual : 文本证据 / textual evidence : sintagma nominal]]\n[[KO: 텍스트와 해석 || 해석 : 解释 / interpretation : 명사；한자어 解釋 ;; 근거 : 依据 / evidence : 명사]]\n[[JA: テクストと解釈 || 解釈 : 解释 / interpretation : 名詞 ;; テクスト根拠 : 文本依据 / textual evidence : 複合名詞]]`,
  economics: `[[FR: Choix sous contrainte || incitation : 激励 / incentive : nom féminin ;; arbitrage : 权衡 / trade-off : nom masculin]]\n[[DE: Entscheidung unter Knappheit || Anreiz : 激励 / incentive : Maskulinum ;; Zielkonflikt : 目标冲突 / trade-off : Maskulinum]]\n[[IT: Scelta e vincolo || incentivo : 激励 / incentive : nome maschile ;; compromesso : 权衡 / trade-off : nome maschile]]\n[[ES: Elección y restricción || incentivo : 激励 / incentive : sustantivo masculino ;; disyuntiva : 权衡 / trade-off : sustantivo femenino]]\n[[KO: 선택과 제약 || 유인 : 激励 / incentive : 명사；한자어 誘因 ;; 상충관계 : 权衡 / trade-off : 명사]]\n[[JA: 選択と制約 || 誘因 : 激励 / incentive : 名詞 ;; トレードオフ : 权衡 / trade-off : 外来語]]`,
  psychology: `[[FR: Preuve et comportement || comportement : 行为 / behavior : nom masculin ;; validité : 效度 / validity : nom féminin]]\n[[DE: Verhalten und Evidenz || Verhalten : 行为 / behavior : Neutrum ;; Gültigkeit : 效度 / validity : Femininum]]\n[[IT: Comportamento ed evidenza || comportamento : 行为 / behavior : nome maschile ;; validità : 效度 / validity : nome femminile]]\n[[ES: Conducta y evidencia || conducta : 行为 / behavior : sustantivo femenino ;; validez : 效度 / validity : sustantivo femenino]]\n[[KO: 행동과 증거 || 행동 : 行为 / behavior : 명사；한자어 行動 ;; 타당도 : 效度 / validity : 명사]]\n[[JA: 行動と証拠 || 行動 : 行为 / behavior : 名詞 ;; 妥当性 : 效度 / validity : 名詞]]`,
  business: `[[FR: Décider et agir || décision : 决策 / decision : nom féminin ;; responsabilité : 责任 / accountability : nom féminin]]\n[[DE: Entscheiden und Handeln || Entscheidung : 决策 / decision : Femininum ;; Verantwortung : 责任 / accountability : Femininum]]\n[[IT: Decisione e azione || decisione : 决策 / decision : nome femminile ;; responsabilità : 责任 / accountability : nome femminile]]\n[[ES: Decisión y acción || decisión : 决策 / decision : sustantivo femenino ;; responsabilidad : 责任 / accountability : sustantivo femenino]]\n[[KO: 결정과 실행 || 결정 : 决策 / decision : 명사；한자어 決定 ;; 책임 : 责任 / accountability : 명사]]\n[[JA: 意思決定と実行 || 意思決定 : 决策 / decision : 名詞 ;; 説明責任 : 问责 / accountability : 名詞]]`,
  daily: `[[FR: Vérifier la compréhension || reformuler : 换一种说法 / rephrase : verbe transitif ;; confirmer : 确认 / confirm : verbe]]\n[[DE: Verständnis sichern || nachfragen : 追问确认 / ask for clarification : trennbares Verb ;; bestätigen : 确认 / confirm : Verb]]\n[[IT: Verificare la comprensione || chiarire : 澄清 / clarify : verbo ;; confermare : 确认 / confirm : verbo]]\n[[ES: Comprobar la comprensión || aclarar : 澄清 / clarify : verbo ;; confirmar : 确认 / confirm : verbo]]\n[[KO: 이해 확인 || 확인하다 : 确认 / confirm : 동사 ;; 다시 말하다 : 换一种说法 / rephrase : 동사구]]\n[[JA: 理解の確認 || 確認する : 确认 / confirm : サ変動詞 ;; 言い換える : 换一种说法 / rephrase : 動詞]]`,
  art: `[[FR: Voir et interpréter || composition : 构图 / composition : nom féminin ;; matière : 材质 / materiality : nom féminin]]\n[[DE: Sehen und Deuten || Komposition : 构图 / composition : Femininum ;; Materialität : 物质性 / materiality : Femininum]]\n[[IT: Vedere e interpretare || composizione : 构图 / composition : nome femminile ;; materialità : 物质性 / materiality : nome femminile]]\n[[ES: Ver e interpretar || composición : 构图 / composition : sustantivo femenino ;; materialidad : 物质性 / materiality : sustantivo femenino]]\n[[KO: 보기와 해석 || 구성 : 构图 / composition : 명사；한자어 構成 ;; 물질성 : 物质性 / materiality : 명사]]\n[[JA: 見ることと解釈 || 構図 : 构图 / composition : 名詞 ;; 物質性 : 物质性 / materiality : 名詞]]`,
  philosophy: `[[FR: Concept et argument || prémisse : 前提 / premise : nom féminin ;; objection : 反对意见 / objection : nom féminin]]\n[[DE: Begriff und Argument || Prämisse : 前提 / premise : Femininum ;; Einwand : 反驳 / objection : Maskulinum]]\n[[IT: Concetto e argomento || premessa : 前提 / premise : nome femminile ;; obiezione : 反对意见 / objection : nome femminile]]\n[[ES: Concepto y argumento || premisa : 前提 / premise : sustantivo femenino ;; objeción : 反对意见 / objection : sustantivo femenino]]\n[[KO: 개념과 논증 || 전제 : 前提 / premise : 명사；한자어 前提 ;; 반론 : 反驳 / objection : 명사]]\n[[JA: 概念と論証 || 前提 : 前提 / premise : 名詞 ;; 反論 : 反驳 / objection : 名詞]]`,
  science: `[[FR: Modèle et preuve || modèle : 模型 / model : nom masculin ;; incertitude : 不确定性 / uncertainty : nom féminin]]\n[[DE: Modell und Evidenz || Modell : 模型 / model : Neutrum ;; Unsicherheit : 不确定性 / uncertainty : Femininum]]\n[[IT: Modello ed evidenza || modello : 模型 / model : nome maschile ;; incertezza : 不确定性 / uncertainty : nome femminile]]\n[[ES: Modelo y evidencia || modelo : 模型 / model : sustantivo masculino ;; incertidumbre : 不确定性 / uncertainty : sustantivo femenino]]\n[[KO: 모델과 증거 || 모델 : 模型 / model : 명사；외래어 ;; 불확실성 : 不确定性 / uncertainty : 명사]]\n[[JA: モデルと証拠 || モデル : 模型 / model : 外来語名詞 ;; 不確実性 : 不确定性 / uncertainty : 名詞]]`,
};

export function courseModuleFor(subject: SubjectId, title?: string | null) {
  const subjectModules = COURSE_MODULES.filter((module) => module.subject === subject);
  if (!title) return subjectModules[0];
  return subjectModules.find((module) => module.title === title || module.titleEn === title || module.id === title) || subjectModules[0];
}

export function sourcesForCourseModule(module: CourseModule) {
  return module.sourceIds
    .map((id) => COURSE_SOURCES.find((source) => source.id === id))
    .filter((source): source is CourseSource => Boolean(source));
}

export function buildCourseModuleDsl(module: CourseModule, mode: TeachingMode, locale: "zh" | "en") {
  const stage = STAGE_COPY[module.level];
  const primaryOverview = locale === "en" ? module.overviewEn : module.overview;
  const secondaryOverview = locale === "en" ? module.overview : module.overviewEn;
  const primaryInquiry = locale === "en" ? module.inquiryEn : module.inquiry;
  const secondaryInquiry = locale === "en" ? module.inquiry : module.inquiryEn;

  const modeSection = mode === "case"
    ? locale === "en"
      ? `## Worked case\n${primaryInquiry}\n\nAnalyze the case in four passes: identify the decision or claim; list constraints and missing evidence; construct the strongest competing explanation; state what observation would change your judgment.\n\n## 案例分析\n${secondaryInquiry}\n\n依次识别判断、约束与缺失证据，提出最强竞争性解释，再说明什么观察会改变你的结论。`
      : `## 案例分析\n${primaryInquiry}\n\n依次识别判断、约束与缺失证据，提出最强竞争性解释，再说明什么观察会改变你的结论。\n\n## Worked case\n${secondaryInquiry}\n\nIdentify the decision or claim, list constraints and missing evidence, construct the strongest rival explanation, and state what observation would change your judgment.`
    : mode === "close-reading"
      ? locale === "en"
        ? `## Source-reading protocol\nOpen one of the linked course sources and read a short section in four passes: vocabulary, claim structure, evidence, and limits. Record one sentence you accept, one you question, and the evidence needed to decide.\n\n## 原典精读协议\n打开下方开放来源，依次检查术语、论证结构、证据和边界。记录一句你接受的判断、一句你质疑的判断，以及作出决定还需要的证据。`
        : `## 原典精读协议\n打开下方开放来源，依次检查术语、论证结构、证据和边界。记录一句你接受的判断、一句你质疑的判断，以及作出决定还需要的证据。\n\n## Source-reading protocol\nRead a short section from a linked open source in four passes: vocabulary, claim structure, evidence, and limits. Record one claim you accept, one you question, and the evidence needed to decide.`
      : locale === "en"
        ? `## Guided inquiry\n${primaryInquiry}\n\nBefore answering, define the key term, give one counterexample, and state the boundary conditions of your conclusion.\n\n## 引导练习\n${secondaryInquiry}\n\n回答前先定义核心术语，给出一个反例，并说明结论的适用条件。`
        : `## 引导练习\n${primaryInquiry}\n\n回答前先定义核心术语，给出一个反例，并说明结论的适用条件。\n\n## Guided inquiry\n${secondaryInquiry}\n\nBefore answering, define the key term, give one counterexample, and state the boundary conditions of your conclusion.`;

  return `${locale === "en" ? "## Core explanation" : "## 核心解释"}\n{{${module.title}|CN}} · {{${module.titleEn}|EN}}\n\n${primaryOverview}\n\n${locale === "en" ? "## 中文理解" : "## English explanation"}\n${secondaryOverview}\n\n${locale === "en" ? "## Learning stage" : "## 学习阶段"}\n${locale === "en" ? stage.en : stage.zh}\n\n${modeSection}\n\n## ${locale === "en" ? "Multilingual concept map" : "多语概念地图"}\n${SUBJECT_TERMS[module.subject]}`;
}
